swvknlHLpjTLMEfUlinrctRoDDQFfERScyBDuUPDLQfRLJrNrzjhTORmAxBQNerCyJwOkCjrIdRfubm382 = 370
Q380 = 203
IllllIllIIllIllIIllIlIlllllIllllllIllIlIlIIllIIIIIIIlllIllIIlIIIlllIllIIlIIIlIIIIIllIIIIlllIIIlIIllIllllIIllIIlllIllIIIlIIllIlIIlllIllIIlIIlIIIIIIIIIlIIllllIIIIIlllIIllllIIlIIlIlllIlIlIlIIlIlllllIIlIIllIllIlIlIlllIIlllIlIlIIlIllIllIIlIIIIlIllllIlIIllIIlIIlIllIlIIIlIIllIIllIllIllllllllIllIllllllllIlIlIIIlIlllIIllIlIlllIllllIIIIlIIIllllIIlIIllIIIIIllIllllIlIIIIIIlllllllllllIIIl = "lAIGeEoufWdEUDWJUbrljOqbGpDinIJsvhAkuwAjkcRgaIzptZMWspxJEpRitAwamAInSEYureUePZO"
sdOxSBWVTWXGOOXBeqolCEcQHLmmdwnZjqGEkDToPRntWXxPkzIuBnGoFlksZGyBXVpjdkZTQIsuoCm376 = 226
R374 = "IrCcOHSHFmsqQfXRgwJrgnkUHSHYnVcIlrsKjNRNKQZWPOHpuQDGRffirQxXNSYYQSIUoIVvKQLVibC"
lIIIlIllIIIlIIlIllIIlIIlIIIIlIIllllllIlllIlllIllIIlIllIIIlllIlIIlIIlIllllIIIIIllIIIlIIllllIlIllIIlllIIIIlIlIIIlIlIIlIIlIllIllIIIIlIlIIlIlIllIllIIIllIlllllIlllIllIlIIIIllIlllIlIIIIlIIlIllIIllIIlIIIllllIIlIIlllllIIIIIlIIlllllllIIllllIlllIIIllIIllIIlIlllIlllIllIIIlIIllIlIlllIIllIIlIIIIlllIIIlIlIIIlIIllIllIIlIlIIllIIIllIllIIIlllIllIIIlIIIIIllIlIIlIIlIIllIllIIllIlIlllIlIlIll = "NqZWTURXNZHBDAHlTSANuaGyqnQAwmwijJKwzDpkUatbrwKZHUTVIJdYEkeswmPNExljBQtBEgZvgme"
b16375898102011971370 = 218
IUKmpTZiKjXAjnDVlXzPLKwHcosyCeuuSNfPHPKCMzICsGDyIthAtCxEmdDZfQWyVdwuBJSQjQCEUUs368 = "mArpNxfFKncMUtZjgKMWfVzFmduOWqwmyroQGCnFcMLIrBlLTrbWsWzLniiyxXzECgvVWZgLyPFKMIu"
O16375898102003984366 = 412
llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll = "vMoajhMPhEKxayYUQhQbXmBjFSDHWgOmYOQjOVwqWIMdzkeruirDinFCJmUzqfjoOZqYbHTYcngUYfV"
o1637589810198433362 = "jiqEogNddSofjYOfizlXnZPeIUzYjuJIKWfMdRsKoeDPoaOpdCzsNItceDCynEvuTnlbThDWQLJKraA"
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = 324
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = 331
Q16375898101964543356 = 291
aAAaaaaAAaAaaAaaaAAAaaAAAaaaaAAaAaAaaAAAAAaaaAAAAAAAaAaAaAAaaaaaaaAaaAaaAAAaaaAaaAAAAaaaAaAAAAaAAAaaAAAaAAAAAAAAaaAaaAaAAaaaaaAAAaaaAAAAAaAaaAaaaaAAAAAaaaAAAaAaaaAaAaaaaAAaAAaAAAaaAAAaAAAaaAaAAAAaaAAAaAaaAAAAaaaaAaAaAAaaAaAAaaAaAAaAAaAaAAaaAAaaAaAAAAaaAAAaAaaAaAAaAAaaaaaaaAAaaAaAaAaAaAaaaaAAaAAaaAaAAAaAAAAaAaAaaaaAaaAaAaaAAaaAaaAAAaaaAaaaaaaAAaaaaAaaAA = 288
IIIIllIIIlIlIllllIIlIllIIIllIlIIIlIIIlIllIlIIIIlllIlllIIlIIlIIIlIIIIIIIlIllIIlIllIIlIlllllIIIIIIlIIIlIlIIIlllIIlIIIIIIllIIllIIlIlIlllllIIIIIlIIIIlllIIlIIlIlIIIIIIIlIIlIIIlIIlIllIlIllIlIIllIllIlIIIlIlIIlIIIIlIIlIllIIlIlIlllIlIIIlIllllIlIIllIIllIlIlIlllllIIlIlIIlllllIIllIIlllllIllIllIIIlllIlIlllIlIIIIIIllllllIIIIIlllIlIlIIIIlllllllIIlIIlllIIIllIlIIIllI = "MnwswdFLFSjNijokQHOHeyiffbJefcoglvGCMFQrBDKzrtqFApKCFhOwHTqblaJINkiISJQKGOTFMNO"
lIIlIIllIllIIllIIIIlllIlIIlIIIllIIllIlllIllIIIIllIlIlIIlIIIIIIIlllIIllIIlIlIIIlIllIlIIllllIlllllIlIIIIlIIlllIllIIIllIIIllIIIIlIIllIIlllIlIlIlIllIIIllIlIlIIlIIlIlIIlIIIIlIlIIIIllIllllIIIIIlIllIlIlIllllllIlIIlllIIlIIIlllIlIllIlIlllIIIIllIIIlIlllIIIIllllIIlIlIIllIlIIIlIIlIlIlIIlllIlIllIIllIlIIlIllIIllIllIlllIIIlIIIIllIIllIlIlllIllIllIlIIIIlllIIIlllIIl = "SQkJHtknJQkzSzefGDnbLaRsuCXCJKpmyMpwNWTmWQQDhVmmHSlvgfhQrRZJiMaUEKRTqVSGDwUVvUE"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = "mtjyKPjeWvPZczWPNhlDzRgSLAPsypJBijuKzXtuwbiFoiXCyVuwCeGMnNgXCmKpTbgKlZaBaQuQsqd"
woHQqABAaPhuPzrPXwgDKGTbcGgcGnPAyYMtrwBJQpwbCzxtVEgJxNPkGLKrMBOfXUCmjFtvTAkJXUg346 = "DFkEdFprwjiwqiLuLvdskpAaDOGfUGVzbnWQKlPHouNacSTzAVtCcSXCtYDFjhfFUlmHcbveSqCSRKX"
l344 = "aSYZospoUfLFAXGFcGbwMFmJdXxXtvbFpgPbUYpNjoWOTAKlrsntGUkKvuViYlLoEkRLEgzduUzClpc"
gYdislSfrkQjQrXxhRZGKHZPXEnyshALqVevEMHnhUhLERbaJOqrOHvTgAgVmBOZqsYqmkUopVVbUzp342 = 375
aAaAaaaaaAAAaaaaaaaaAaAAAaaaAAAaaAAAaAAAAaaAAaaAAAAaAaAAAAaAAaaAaaaaAAaAAAAaaAAAaaAAAAAaAaaAaAaAaAaAaaAAaaaAAAaaAAAaAAaAaAaaaaaaaAAAAaaAaAaaaAAAaAAaAAaaAAAAAAaaAaAaaAAaAaaaAAaAaaaAaaaaAaaaAAaaAaAAaaAaAaaaAAaAaaAaAAAaAaaAaAAAaAaAaaAaaaaAAaAAAAAAAaAaaaAaaaAAAAAAAAaaAAaaaAaaAAAAaAaAaAAAaaAAaAAAAAAaAAAaaAAAAAAAAaAaAAAAAAAaAaaAAAAAaAAAaAAAaaaA = "dkaiHJmNCoMryTFBWkaKBgZJIWmezhxrZLDmRkNpnIJynNUThPzNVaMFaMxTFNJiOvZnBQdnDjRzjDd"
aaAAaaaaAaaaaaAaAAAAAAAAaAAAAAaaaAaAaaaAaaAAAAAaAaaAAaaAAaAaAAAaaAAaAAAaaaaaaAAAaAAaAaaAaAaAaaaaAAaaaaAaAaAAaAaaaaAAAAaaAAAaaAaAaaaaaaaAAaAAAaAaaaaaaAAAaaaAaaaaaAaaaAaAaAAAAaAAaaaaAaaAAAaAaaaAAAaaaaAaaAAAaAAAaaAAaAAaaaaaAaaAAaAaaAaAAaAAAAaaaaAAAaaAAAaaAAAaAAAaaAaAAaaAaaaAAaaaaAaaAAaAAaAaaaAAAAaAaAaAaAaaAAAaAaaaaAaAAAaAaaAAAAaaAaaAAAaAaa = 815
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = 522
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = 578
ycgLeoZofGPjkiijbntkvjsKXpgDWOqslIyoimbGyPMvQosgOdBIOXmyTpZjwtBdKfnZeBMUtXgLprm332 = "uMBiDMivbtfIYmBOAgenUXucJGrNXmOfVzNpZOEDfEgMfUJIuNmdlIebriIWSPZvBivhofmjvclXHTN"
k1637589810178617330 = 268
aaAAaAAAaaaaaaAaAAaAAAaAaAAAAaaAaAAAAaaaaaaaaaAaAAAAAAAAaaaaaAaAaAAaaaAaaaAAAaAaAAAaAaAaAaaaAAAaaaaaAaaaaAAAAAaAAaaaaaAAaaAAAaAAaAAAaAaaAaaaaAAAaAAaAAaAaaAaaAaAaAAAAaaaAAAAAaAAAAaaaaaaaaaaaaaAAAaaAaAAaAAaAaAAaaAaaAAAaAaaaaaAaaaAAAaaaaAaAaaAAaAaAAaAAAAAAaaaAaAAAaaAaaAAaaaaAaaaaAAaAAaAAAAaAaaAaAaaaaaaaaaaAAaaaAAaaaaaaaaaAaAAaaaA = "LcESElrlFkdcsRGQZLzakMuibVAFoMeHIQjIHWlnqTOgnuHjbmGvjUBvsNGGLevoKYFGCXfTVOoWGyY"
IlIlIIIlIllIlllIlIlIlIIIIllIIIlIIllIIIllIlIIllIIIIIIIlIlIllIIlIIllIlllIIIIIlllllIlIlIIIlllllIIIllIlIIIIIllllllIIlIlIIIlllIlIIIIllllllllIllIIlIlIllIllIlIllllIIllIlllIIllIllIllIlIlIlllIlIIIIlIIlIlIIllIlIllllIIlIIlIIIIlIllIllllIIIIIIlIIIllIlIlIlIllIllIllIIIlllIllIIllIllIllIIlIlIlIIIIIlIlllIlIIlIllIlIlllIlIIIIllIlllIlIIlllllIIIl = "KkgFmECQJDtYACLGHpYEhBUuAkAOoVFQfQlZMoTzppRchMDxcrZdDhoMrjqcfZWXFbFIQABZttcBwJw"
I16375898101767445324 = "OGPEmpcJsdjBqouvpcZHqxXPcTMSapeobUvjMaYifJsxQhutSUfHMUwRIIQsiDWzIcAvzQOUyhyjsfj"
AAAAAaaaaaaAaAAaAaAAAAaaAAAaAAAaaAaaAAAAAAAaAAaaaaaaAaaAaaAAaAaaAAAaAAAaAaaaAaaaAAAaaAAAaaaaAaaaAAaAAaAAAAaAaaAaaaaaaaAAAAAaaAAAAaAaAaaAaAaaaaAaaaaAaAAaAAaAaaAAAaAAAAAAaaaaaAAAAaAAaaAaaAaaaaaAaAAAAaAaaAaaAAaAaaAaaAAAAAaaAAaaaaAaaAAAaaAAAAAaAAaAAAaAAaaAAaaaAaAaAaaAaAAaaAAAAAaaAAaAaAAaAAaaaaaAAaaaaAaaaAAaAaaAAAAaAaaaAaaAaa = "UGykLVWsWElyHkwNREPJxjOcSohbjUqeYVMDQUDUyfFIlqeWlXOVOmBZSNgDkhTvAvPvCRtRLRtnDVY"
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj = 335
V318 = "DonkJieovnkqpRyGbTfOaaHvcnEKpphPLfgPUsKwgDkTKnXoDoXMsRLpHcnLdSCHbmHPfsGUohzjuTK"
ulYopPfHYVegTlzxpFuSAkolQxESZYwyPDjUgpgslOEtakiSwxBhGYofqbiXqbNgmsMIlzFOcvjEWod316 = "mfekOMdESlbnXvwcxngVgXPPKEPKcGuBuSXFgOeqvgpFujQCpcWFZcNvpWsGQyIlkokUkCILVaEKgUG"
g16375898101696377314 = "voazuUGxMSYWrmwPWVCqXPdVQtidwxuWvtyBkGPAJTcKXnGuiXRdXecKHGCCpBVodUFONwmVeNlYMbM"
ztXoWzZzgbbJygOZoxJqMLLiVNyReGxLIWGodXOtCFcOFhlbLlOwaGeyTckEhLnwVpTTjSZrRKRpXKL312 = 241
h310 = 392
ynkjpCYgoWFDMoCoZsPJtDxnYFMdJgAZvVRJzbrXdQzNSBBbjtYhckAFdvCbKkXEjNbOaPBfdwRuCyX308 = "ZhUZXFdueDNdxUahmjIPIWiwrAMNbkBkNlzapHluGTPNsBdNoEXWtEtvMVHRxwGfmOfDxhdaEiLRVBo"
n306 = 140
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = 372
lllIllIIlllIlIIlIIlIlIIIllIIIlIlIllIlIlllIIlIllIIIIIllIlIlIlIlllIIllllIllIllllIlIIIllIIllIllIlIIllIllIlIIIlIIlIIllllIIIllIIllIIIllllIIlIIIIIIllIIlllIlIIlIlIllIlIllIlIIllIIllllllIIllllIllIlIlIIlIlIIlIIlIIlllllIIlIllIllllIlIIIllIIIllIIlIIllllllllllIIIllllIIIIIIlIllIIIlIlIlIlIlllIIlIlllllllIlIlllllllIIII = "vtCzkkMrtLWeeIMOSfgUZrFbHhdxEYieIcxqGoBMeWsdgvpSIywGqpKREIHvNkUKSVocsvhNztTFVNw"
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD = "utmcnrjXOCRqPferbWkJqCFBCqcoNzATwqzflbfeoqZifuzZmderIRwMBZstMdvgHVqtkygvacxFSvo"
S298 = 912
NNnejoBrnQGWaXTbIkEkMiDLKqkLKbzKGfbEJUNxXlVHduOnUClacXtnBqDIXLGbIPsgUuwKqIKHyaK296 = 86
lIIlIIIIIIllllIlllIlIllIllIlllIIlIIlllIlIllIIllIllIIIlIIlIlIIIIIlIIIllllllIIIllIIlIlIlIIIllllIlIIIlIllIlllIIlllllIlllIIlllIllIIIIIlllIIllIlIIlIlllIlIIllIIIIlIllIIlIlIlIllIIIllIllllIIlllIIIIlIIlIIllIIIllIIllIIllIIIIIlIIlllIIIIIIlllIIIIIllIIIlIIIIIlIIIllIIlIlIIIlIllIlIIlIllIllIIIlIIlIIllIIllllIl = "YiDcdhmXYorvrWOaFOjXsdQTjBPxAqRyJpqPAuSqrMWPEaHJcQTELIpnQevrtGbfqAyXqXKrMPOSErO"
IlllIlIIIIIIIlIIlIlllllllIIIlIIIIlIIIlIlIlIllllIllIllIlIlIIlIIllIllIIlllllIlIIllIIllllllIllIIIllIlIIllIlIIIlllIlIIlIIllllIIlIlllIIlllllIlIIllIlllIllllIllIllIIllIIllIlIIlIlllIIllIIlIlIlllllIIlIIIIlIIIllIIIIIlIllIIlIIIIIlIlIIIlIllllIIllIllllIIlIllIIlIIIIIllIIlllllIIIIllllIllIlllllIIlIlIllIIlII = "bjQaNBCgCYVzRtfITKFrcJvAhlEzYfbeTeKgaxMjcICoqlGFMLjqQLKqrjUqLZHxStctlATpUUUiNKn"
lllIlIllllIIIIIIIIlllIIIIIlIIIlIllllllllIIIlllIlllIIlllIIlllIllllllllIIlllIIIIIllIIIIIllllllllIIllllIlIIIIlIllIllllIllIlIlIllIlIlllIIlllllllIlllIllIIlIIIIIIIIlIIIIlllIlIllIlIIllIIlllIlllIIlllIlIIIIIlllllIIIllIlllIIlllIlIIlIlllIIllIllIlIlllIIIIlIIIlIIIlllIlIlllIlllllIIIIlIIlIlIIIIllIlIIIlII = "BHelugqbGfWsCFXwSDJdJRZwZPyUOBQxqUuOKGpeCdjgvLXGwKeGYVoNDhVzciGrSASJGJEJqAJPdZa"
sHbcmRfgsDIVKLPkaoSoNqeNxlVYozeXtaBdrVDaFdaZaFVDUaeiuoCXgwTwJPzIBWeiCaOPtBAfiWO288 = 386
MtnDbFOlIYsGPwSDtFbwRhenMbFFNthwISfqoKBcREzEkGigTXBSHlJyndlVVnpgJQUYnDTTzTsKwlx286 = "FDIiJAbMYCqIFsGAiGDBXeUGQcBKGhjiBWaYZZDVzswnJkQERPruDwcNErVbroCfBbFRnZYaXYIFkIB"
AAaAAaAaaAaaaAAaAAAaaAaAAaAaAaaAAaaaaAAAAaaaAaaAaAAaAaaAaaaaaAAaaAAaAaAaAaaAAaAAaaAaAaaaaAAAaAaaaaaaaaaaAaaaaAaaaAAAAaaaAAAaaaaaaaaaAAAaaAaAAAaaaaaAAaAaaaaaaaaAAAaAAaaaaaaAAAaAaAaAAaAAaaAAaaaaaaaAaaAAaAAaAaaaAaAAaAAaaAAAaAAaaAaAaAaAAAaaaAaaAaaaAaAaaAAAaaAAaAAAaaAaAAaAAaAAaAAaaaAAaAAa = 292
CpWoGGBtJfBHjGnHgySyWYYLzYOzPQaoteRwKAMvRgDJHvgBPfmkFlzMxIJAiLhBgImKesqVggRyajo282 = "LvNwAetXemADuypSaFFcRWEKwKyUzeYwlgNnawHrMmbNixYEEkqOrihBHpbrmrrCOEECwRiHOdwPHHN"
D280 = "eOHVzVOmQkAuKlfQFOrjNhzsevFYNREXwoZUljuRtDVWWzJObsQFMeSTLAbeoEsxNvxuOWZMagUZPKf"
lIlIIlIIIIllIIlllllIIIlIIlllIIIllIlllIllllIlIllIIIIIllIlIIIlllllIIIIIIllIllIIlIIllIIIlIIlllllllIIIIIlllIIIIlIllIllIlllIIlIIIIlIlIIIIIIlIllIlllIlIllllIIIlllIlIlIlIIlIlllIIIlIlIlIIIIllIlIIlIIIlllllIlllIIlIIIlIlIIIlllIllIIllIlllIIlIlllllIllIIIllIlIIlIllIIlllllllIIIlllIIllIIIlIllll = 503
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = 622
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = "PbvZeqZdCKpcBYjDJaFnbtviVopQBYLSotXJQVUPxYFLyflfBMxewbzdZvAaebpZPfAHPPHMDcpHcko"
aaaaaaAAaAaaaaAaaAaAAaAAaaAaaaaaAAaAaAaaAAAaAaAaAAAAaaAAAaAAAaaaAAAaAAaAAaAAAaAaaaaAaAAaAaAAaAAAaaaAAAaAAAaaAAAAAaAAaAaaAAaaaAaaaAAAAAAaAaaAaAaaaAAaAAaaaAaaAAAAaaAAaaaaAAAaAaaAaAAAaAAaAAaaAaaaAAAaAaAaaaAAaAAAaAAAaAaAAaAAAAaAaaAAAAAAaaaAAaaaaaAAAAAAaAaAAaaAAAaaaaaaAAAaAAaa = "GyJEKfmfwgrlZJzkkrjjKrOBKDgQywvTGLEYmPryyyczOEzooiiQgMLXrCZlMddZElCdlCOPsguCyke"
AaAAaaAaAAaAAaaaaaaAAAaaaAAaaaaaaaAAAaaAaaaAaaAaAAaAAaaAAaaAAAAAaAaaAAAAAAaAAaaAaAAaaaAaaaaaAaAaaAaaaAaAAaAAAaaaaAaAAAaAaAaAAaaaAaAAAAAaAAAaaaAaaAAaaAaaaAAaAAAAAAAaAAaAAAaAaaaAaaaAaAaaAaaAaaaaAAAaAaaAaaAaaaAAAaAAaAaaAAaaAaAaAaAAaAAaaAaAaaaAaaAAAaaAaAAaaaaAaAAAAaaAaAaAaa = "mqPEtmZgsEyDTPVFDNkLiQRvigstjGnBiyPooUPLjCkUgMVHmhzsMIiTanxYbUPxTHvxMUJYcnlcbaw"
IlIlIllllIllIIllIIllIllIlIlIIlIIlllIIIIlIlIIllllllIIllIlIllllllIllIlllIllllIllIlIIlIIIlIlIllIIlllIlIlIlIIIlIIIlIIllIIlIIIllllllIlIIlIlIlIllIlllIIllllIlIIllllIlIIIlllIlIIlIlllIlIllIllIIIIlIlIllIIlIIIIIIllllIIIIIIlIIIllIIIIllIlIlIIIlIlIIllIIlllIlllllIllllllIlIlIllIIIllI = "GJUKqkgbuJlAnwNoRHQYEfuFojXxLGwMSziBpJBQdlaCBNAGyxElXhtUZlFYyTTNhQeUAxQSFDvWKNL"
u16375898100948498266 = 215
D264 = 599
I262 = "nOqfvwNdgHyclGQoIeuFIhOBgWRaVqbauBUIwwUKONbYHZitBPTAZLeQpSBJaxOhBYoZloxYgcCkymU"
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = "jlEQTszUvcEKGNkZRSqhXHohVfRuEcBluriJcUnJezAPDBoAYFOVxJCPdehNjipOUWGSinBryPyVFTY"
KIErBAmZkiGIEhYeZRwDonfnjxuhVThxUXBsxJOKOYpadzCWXwlQeYiGFEUxVzZCMGtlTtApHTwDyRh258 = 243
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = "reFlKjqOwbmyFyNCLmkUdbbpIOfXXfzhmUivKJOZgYxpHJwNtGRvGDCbAPGIHeHPWSUSkBcGBxSNIjM"
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV = "dBrmYXgtExBPeWOkvYuDFfnllcHzOwcfnmZfkwrZZxaUjtGmajFOtNyoNXPdFvanNFRSAQMyJsCFCVi"
I252 = "zLDnLiHQwoVhbfuuHxKtMCLjniZLVmooXgGNZoTNybGqzoAXxdipITWzUOKQSInZiwcpFMSPiBydEmo"
aKndgtdthxQxrciCwEkgogoAwRGaXAMZLaweKZosUVKeqIUykTAOgsmyVxsGCBfGzwEjVIekBYmGSlo250 = "YywgzEYEvNqxvrFGgdJsOEHeWjblWJNVEmnmGoBbtaTPlKuEZUfYBZGlbdngmmdDmGWWKnzdEhLtiNt"
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 273
LGRbTRkzGEZeqJCSbyEKjOVvQsXBsIPrthDaaVidWyMxONfaZicmmZkzXMSckRXZcCKPCiIwqkRDXBs246 = 390
aaaaaAaaAaAAAaAAAAaaAAAAaaAaAAaaAAAAaAAaAAaAAAAAAAAAaaAaaAAAaAaAaaaaaaAaAAaAAaaAAaAAAAAAaAaaaAAaAaaaAAaAaaaaAAaAaaAAaaaAAaaAAAaaAAaAAaaaAaAaaAaaaAAaaAaaAAAAaAaAaAAAaaAAaAaaaAAAaaaAAaaAaAAaAAAaaAAaAaAAaAAaAAaaaaaAaaAaaAaAAAaaAAaAAaaaaaaAaaaaaAaA = 97
vzwLyMTfyiTeBldrlKfIdBDytpvMGfqohbNbpDeaLWxueOoYflVwZPmWUXovUfXbOoZWFQYVFflJwqZ242 = 127
U240 = "ZvwemrGDezxZHfJVtyjxgXaaZcvxaBNaHzjfQXpSNevdBYTRbWXxsUwXGyCCUOAmoViAogJcpmixOYt"
AaaaAAAAaaaAAAaAAaaaaaaAaaAAaaAAaaaAAaAaaaAAAaaaaAaAAAAAaAaAAaAaAAaaAaAaAaaaaaAaaAAAAAaaaAaAaaaAAAaAaaaAAaAAAAAaaAaaaaaaaaaaaAAaAaaaAaaaaaAAAAAAaaAAAaaaaaAAaaAAAaaaAAaAAaaaaaAaaAAAAaAaaaAAAAaaAAAaaaAAAaAaAaaAaaAaaAAaAaaAAaAaaaaAaaAAaAaaaa = 284
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 689
o16375898100707965234 = 157
Q232 = "zPMaYiCAQNMpivXUAJTexWOBQDoZDhtAdqyoQFggGgsBvTYgtamWayNpWUlzaOvnizViHbadaTzYDAz"
m16375898100679765230 = "DptQSVUAsIMhEVddCDfXBiEtiVTGKvkYDQQEvTsxwEMeobKViJgXCzbTsrVNBwMSOqiciLHFaKqmIac"
I228 = "izCpWEHqxmngRTMukVbVqQglxbeYyPkvvOfyWyhXDsJaGhdTvgRCeJXBxpXBnmNUDKLtqGKwHbPkrFQ"
H226 = "HHSrgbfINFGgZAZyXpEzOUaZnlpPpKMBumwCBfiKcWKZyAdHrQlKlpTfSkjvqEDwHqSlyQVPzrLqWVr"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = "eFviuCcxqTThHHQQNmewwdfhaOKKOadJqPDKnGmeFZqGNyZKqoQlEbSJbrWHOTcTFBVSiCyiLKpaAOr"
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = "ndFoYaPIApimdTCWdJmSiWNOaelXfmrNVTTUQZxSxzKbKipRNvxOSPoGtmKWsYFKjbSKgQyCirRmapT"
llIlIIIllIlIIIllIlIlIIllIlIIIIIIIIlIIlIIIllIIlllIIIIIllIlIlIlIIlIIlllIIllllIlIIIIIlllIIIIlllIIlIllIlllIIllIlllIlIlllIlllllIIIlIIllllIIlIIllllIIlIIIIlIIllllIlIIlIlIIIIIIllIlllIIlIIIIlIIlllllllllIlllIllIllIIlIIIlllIllllIlI = "YOtWCSplYAeVYBACBREzxvCVTiBxEAcfcIyqyROHOTExdniLOpahcnVLjVUIznuCwnCFIjRFjujlnos"
aaaaaAaaaaAaaAaAAAAaAAAAaaAAAaAAaaaAaAAAAAAAAAAaaaAAAAAaAAAaAaaAAAaaAaaAAAAaAAAaaaAaAAAaaAAaAaAAAAaAAaaaaaAAaAaAaaaAAAAAaAAAaAaAaaAaAaAAAAAaAAAaAAaAAaAaAAaAAaaaAAAaaAAaaAAAaaaaaaAaaAAaAAAaAAaAaAAaaaaaAAAAaaaaaaaaaAaAAA = 731
AaAAaaaAaAAAaaaAAaAAAAAaAAaAaAaAAaaAAAaaaAAAAAAAAAaAAaaAAaaaaaAaAaaAaaaAAaaAAAaaAaAaaAAaAaaaAaaAaaaAAAaAaaaAAAaaaaaAAaAaAaaaAaaaAaAaAAAAAaAaaAAaAAAAaaAAAaAAAaaaAaAAaaAAaAaaaAAAAAAAAAAAaaAaAAaAAAAAAAAAaaaAAaaAAAAaaaAA = 637
P16375898100600123214 = "tCnrtKtIXBnqlYzEbIxOxrtZPmWJRYMuUnoWUbvcBkwSmhhDMxvIeDDSpASEKkINrkIpDBOFJBmSMFl"
jRbJyPdTSbUsAtKyaIPjdPyiTsFQiKLcbVEJYurNWBFRnlcZHdoEYyBNUGYJAnGzcDeWZdliwAplMfC212 = 272
aAAAaAAAaaaaAaaAAaAAAAaaAaAAAAaaAaAAaAAAAAaAAaAAAAaaAAaaAAaaAaaaAAaaaaaaaAaAaAaAAAaaaaAAAAaaaaAaaAAaAaAaaAaAaaaAaAAAaaaAaAAaAAAAaAaaAaaAAaAAaaaAaAAAaAaaAaaaaaaAaAAaaaaaAAAaAAAaaaaAaaaaaaAaAaaaaaaAaAAAAaaaAaAaAa = 616
bnrBdKnPcMsmcLnSsIAGzTJCfEiOnldGKJErYPyfGxznUTRfWeCuCMrzosqrTcfLkODpIkDMZeSjztm208 = "KLYBWwLmHxrBMvbSCfrHvAkECSuXcHSEpbkMUmofNLNWFhoSUaLQPLtOyzNUWKPLCFNqrcEBUKfBGUX"
S206 = "NAQmFUagTgcDluDhLBzKiXmyAejthMuKgTMoVghSwlmCpQYJUQMKuQpLefXInhRLkZJcnpNPGZJSMNG"
IlIlIllIlllllllIIlIlIlIlllIIlllIlIIlllIlIlIlIlIIlIlIlllllllllIIIlIlIlllllllIIIllIlIIIlIIlIlIIlllIlIlIlllIllIllIIIlllIIIIIIIlIIllIIIIIIIllllIIllIlllIllllllIIlIlllIlllIlIllIllIIIlIlIlIllIIIIIIIllllIIlIlIlII = "TFpRpQcpDEPAqLDVtlPpxEbjNtQtImjagIRWvGfCQPSocfLaekpJQbIWWvZUBjiZrjwnWEJMwTcSwfE"
i202 = "eIsIiWWtmdTCUznZZceKEBtuSpmUrIMtHYYByiJzHzurOSwLRsnunJYSLeCeJVEoeEaaPcqYIcDPHvE"
A200 = 306
y16375898100381246198 = 269
YZIIbEzpDCPylDeszyqVYNRnWxsAJqvMDgHhAyipnZTuPTiAMNnGKdUmTHGOXutVcSlzuzYiHpxneOu196 = "rdGBftDScULYMOcbvYvaAjNWjsGnlKVBTBqwPBxwmldyxlxbMTPSKQdpFMpIvHzxMbQsBLBQDyQdQPh"
aaAaaAAAaAAaAAaaaAaaaAaaAaAAaAAAaaaaAAAAAAAaaAaAaaaaAaAAaaaaAAAaaaAaAAAAaaaAAaaaaaaaaAAAAaaaAaAAAaAaAaaAAAAAAaAaAaaAAAAAAAAAAaaaaaaaAAAaAaAaaaaAaaAAaaAAAaAaaaAAaAaaaAaaaaaAAAaaAaAaaaAaaAAaAaAAaA = "LeXwKZApOWRffcfjGftHWhcFkutPVIsEdPeYxvRcjfpvKwORMrNurGnOzJuUHxONQCvsRiEclafYJCA"
aAAaAaaaAAaAAAaaAAAAAAAAaaAaaaaAAaaaaAaAAaAaAaaaAAAaAAAAAAaaAAAAAaAAaAAaaAAaaAaAAAaAAaaAaAaAAaAAAaAaaaAaAAAAaaAaAAaAAaaAAAAAaaaaaAAaAAAaaaaAAaAaaaAAAaaAaAaAAaaAAAaAaaaaAAAaaAAAaaaaaaAaAaAaAAaA = 393
llIIlIIllIIlllIIIIlIllllllIllllIIllIIlIIIIIlIIIllIIIlIIIIlIlIIllIlIlIlIlIIlllllIIlIIIlIlIIIIIlIlIlIIllIlllIIIlllIlIlIIllIIlIlIIllIlllIIlIIlIlllllIlllIIIlIIllIlllIIIlllllIIIllllIIIlIIIlIlIIII = 306
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = "RBwzSgMeQbYLJYChyrYSDQJFUMKMNbEaboDiUrmjvdQrEWJSflDJbLNniyNuoQelVXDyNehXwaqpsjU"
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN = "xrZayoJCSppQUmFTutOYGKLhqVoCslheBgYFXqiPJyFNbcEhOgvjmLLDMYPwQPulEfsywWSbdpxJOmy"
Q184 = "pmgtLPLuKJYnyOHvESRtOkpBSsKABDjuLNAnaZsaEFIaLPZrojqyldmZeACqKYEmVkhFTkkTjHfntYA"
IIlIIIllllllllIIIlllIlIIlIIlllllIlIIlIIIlllllIllllllIIIIlIllIIllIlIlIlIlllIlIIIllllIlIlIIlllIllIlllIlIllIlllllIlIlllIllIlIlllIlIllIllllllIlIIIIIIlIllIlIlIIIlllllllIllIIllllIIIlIIIlII = 499
AAaaAaaAAAaaAAAAAaaaaaaAaaaaAaAAAAAAAaAAaaAaAAaaaAaaaaAAAAAaAAaaaaAAAAAAAAaAAaAaAaaAAaAaAAaAaaAaaaaAAAaAAAaaaAAaaaAaaAaaaAaAAAAaAAAAaAaaAAAAaAaAAaaAaaaAaaAAAAAAAAAaaAAAAaaaAaAAAAAa = 326
a1637589810015403178 = "iczoFVryCcaLoNoOhVgYJQYXAIDcZiSNoHWVzSRdzEDdsocBGqrsxXYrWUVpGGlgWyzUhBMvPVrNsou"
IixWmvVXHtRzmcLnUYErDjZQWcSKfKhUxkcrqJAvEloyEgNlKCNYsnbAVSKstJgDExbtzMQkcXVhybF176 = "kRmHXcwsnchLBAoOOjXdOlbqUkEqXwkWhKQlnOYbxdTsKdBnRdWUwmKKvDqIGKRGzrgYWECHOQUaGEj"
zepCEbZrCpGfjkdVOOtgPOItHaYwgjhddmfCZNdTrOewLLxyxGAfwGWJiwmPOThtzrrUpuwKRqJIiho174 = 644
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = "NEIRgPCyWVGRBKHqTQrifYSUOmdIaYADNxnsmbbYIdHTRWohFarUCzliFyPalVAhsubkyjkrtDZaQRj"
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = 329
QGjfiaItGbVbJpirXaOWSCvyWsZFyEdKyjwPhUPMxtHJuWAfgzxGffkLZIgBDaXztbsgrQlXeVECysu168 = 440
zsGcZFadmORMLbbHObtHTYBJBhkzmpSIfbhymFyNDqrPDDuaCCMWyOIeYmtiNOWUcspMNmbpUsxZjVO166 = 363
a16375898100133886164 = "GfIkkIiHnRIJhuIbFGzhnFcIQTgfTMLGdsZlSjUXndDOyyeDcFuewjOVQSesDfZeyCRTqrpLNdrQNvZ"
aAaaAaaAaAaAaaaaAaAaaAaaAaAaAAaaAAaaAaaAaaaAaAAAAAAAaaAaaaaaAAAaAAAAaAaaaAaAAaAaAAaaaaaaaAaaaAaAAaAaaAAaaAAaAaAAaaAAAaaAAaAAaAAaAAaaaAaAAaaaAAaaAAAAaaaaAAAaAAAAaA = 642
w16375898100128026160 = "MkPiSAcaHpFNhmcjMrLyKOvsYiNnwRZyovZLMKLvJhAeVItJWoWlTXWQOBqELMbzYYqgWJPVeadsmNH"
aAAAAAAaaaAAAAaaaAAaAAaaaAAAaAAAAAAaaAAAaAaaaaAAAaaaaAaaaAAaAaAAAaAaaaaAaaAAaAaaAAaAaAaAAAaaaAaaAaAAaaAaaAAAaaaAAaAaAaAAaaaaAAaaaaAAAaaaaaAAaAaAaaAAAAAAAaAAaa = "xudFRaBnBiMlwFFJkdGKqPVXGamTecGJJmtMBtNDIcPkHDQFvapjlZGieIpDgaTIOpVQHKaFZFQNyOT"
M156 = 546
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = 361
M16375898100079248152 = 342
IIIIlIlIIIllIlIIIlllIlllIlIlllIlllllllIlllIllIIIIlIlIlIIllIlIlllllIIlIlllIIIIllIIIlIIIlIIlllIIIIlIllIIlllIllIlIIIllllIIIlIIlIIIlIIlllIlIlIlIllIllllIII = "OXjQlksLuGeMnjPAcjBcbmyoldgPinGLoMCelhuezNmjwQthdDBICHhlttFUDCRmfxVeVoTHHXieLXk"
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = 487
lIIlllllIlIIIIIIIlllIIIIIlllIIlIIlIIlIlIllIlIIIIIIllllllllllIIIlIIllllllIIlIlIIIlIIlllIIIIllIlIlIIllIIIlIlllIIlllllIlIlllllIIIlllIIllllllllllIlIlI = "jJdFWmMUpebFsMeJIXsnFgrCaNhEnQzUsjjSYqYLEJVRVlkcjXbdaFhMdNwvMAjkcoygwmUPhSQHuFV"
ykLjOucoRQqBKazdYmUqVIYyGdUKrGOAokNoLHqQRlTlZTODObdSRmvFxHiPyTVIBGFEmrnmnLfTypI144 = "NwwMkkXxIUwtnUDZvCRsxAXFLcMarnmPFbpHndxEkyuPVTfehrzgXUpvtYLBLqUvunowyHlkGcEIozH"
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv = 673
AAAAaaaaaaAAaAAAAAaAaaAAAAAaaAAaaaaaAaaaaaaaAaaaAaAaaaaAAaAaaAAaAAaaaAaaaaAaAAAAAaAAaaaAAaAAAAaAAAAaaAAaAAaaAAaAaaAaaaAAaAAaAAaAaaaaaaaaaAAA = "KkjdLuyTmlZiJODKzKrbYeTBhPyNSXfcujacraoFufnpLOFOVjIkufzrwEqDQbDYLGjueTVMUXtFMNT"
AaaAaAAAAAaAAaAAaAaaaaAAAAaaaAAAAaaaaAaAAAAAaaAaaaAAAaaaaAaAAAaAAaAaAAAAAaAaaAaaAAaAAAaaAaAaAaAaAaaaaaaAAAAaaaaaAaaaaaaaAaaaAaAAaAaaaaAAAA = "QsnVtxpYYZkksmYDelDbPyjrEUOCWtlOlgbVHWRrMBCWAlHRhfVkOCsbQVKVmXBPwyrtXACNxMANHPQ"
AAAaAaAAAAAAaAAAaAaAaaaAAaAAAaaaAAaAAaaAaAaaaaAAaAaAaAaaaaAaaAAaaAAAAaAAAaAaAAAaaaaAaaaaAAAAaAaaaaAaAaAAAAaaaaaaAAAAaaAaaaaAaaaaaaAAAaaa = "HBCDTuFDGkahwbbWyMhddsuRlNVPrjJpOiDkSJwxgthONrCipdPLvwtJvynclIzfAOTNnqSCFMxszFv"
o134 = "zqDnyfKNDVOlpCILEYgsmiTMXlxWlrCGEneIsiThWCWWCwNhrIWhsufobSKqVyFpFABRDnmpthUrITl"
lIIIlIIIIllIllIIllIIIlIllIlIIIllIIllllIIIlllIIlIlllIllIIlIllIllIIlIIIlIIllIIIlIIllIllIIIIIlIIIIIlIIIlIIlIlIlIlIlIllIIIlIIllIIlllllIl = "wLuTwZCvxWxgIBtrMEvhmOtheSIqOfZarfTdohljmGMptALzLzmIeKwTdbGQwKnKkYnJtqIsNuXjTeX"
aaAAAAaaaAaAAaAaAaAAAAAAaAAAAAaAAaaaAaaaAAaaAAAAAaAaaaaaaAaAAAaAAaaAAaaaaaaAaaaAAAAAAAaAaAAAAaAaAaaaAaAaaAaaAaaaAaaAaAAaaAaAAAaAaa = "SpDeqhsiuGMvEbFrIoSifqEfvSLKwddlvTTbnxXqELeMBqUTjrdzsueggPWaOJztqstDOmVPOhXbzMF"
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB = "oHuPvXOzqdWirrZgchHDVWkmofEfTTWTpENpssCEsGmPuTvIuhoSndDCGoMnTdlzPlChzsIULvQryvz"
lllIIIIIlIIlIlIIIIIlIllIlIIIIlIlIlIIIIIlIlllIlIlIllIIlIlllllIIIIIIIIlllllIIlIlIIlllIlllIllIlIIlIlIllIlIlllllIIllIIIlllIIlIllll = "tuoyvJuKRGguHgtHRZBOnNEAGAnadBEvBsXyTAeEEfdhHHKqVGBaeAFIACwxtnLKZsLFbGatGDWZgZm"
c124 = 384
llIIIIIIlIlIIllIlIllIllIIlllllIIIIIlIlIllllIIIIllllllIIIllIlIIlIIlIlIlIlIIllIllIlIIlllllIlIlIllIIlIIlllIIIllIIlIlIIllIllll = 226
B120 = 369
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "tKuIffxeSqosNUVqOLITXVUfAQfrEflGdyeoDiKbxpGDwYkDvqIjtTjNwLQWyjXTYSBljgVwdkGwuXy"
lIIIlIIllIIlIIIlIlIlllIlIIllIlIIIlllIllllIllllIlIlIIIIlIlIIlIlIIlIllIIIlIIllllllllIlIlIlllIIIIlIlIIllIlllIlIIIIlIIII = "IJLqoiFOdbWYVUIcoyCTwObPeePkZWNpaNdmvWJpycUOSYadFmAICRCKZACczMINRkyijGIGhTClVWG"
BQeDQTrYIBDlMJSlarsEFiCEZzkZKqkJEXCDZXOqiyqLyWDBYGrhCaGZaoNRcxdvDHyneFviBUOvRHA114 = 571
IllIIllllllIIIlllIIIIIllllIllIlIIIllIIlllIlIllIIIllIllIIllIIlllIllIllIIlIIlIllIIIlIIllllIllIIlIlIIlIllIllIIllIIl = 326
aAAaAAAaAaaAaAAaAaaaaAaAaAAAaAaAAaaaAAaAAAAAAaAAAaAAaaaAaaaaAaAaaaAAaaaAAaAAAaAAAaAAaaAAaAaaAaaaAaAaaAAAaAAAaa = 937
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV = 406
IIlIIIlIIlIlIlllIIlIIlIllllIIlIlllllIIIlIIIIlIIllIlIIIIIllIllIlIIIIIIlIlIlIllllllIllIlllIIIIlllIIIIlIllIll = "MPRYprkVnDdHGabRNPgGwlsFBylVxPpmDSTqdKcRHdBqUCZlWFmmADBxmZeapGqBrCuzhEjGdqfWxyE"
keHsyQLSAEnfDiLAweTGMJbiYxvAydatfhsiXAyKwoTitppSbaUiuRiJlwpiGARDOFpyuOYCrmwHjXY104 = "EpUlHLzautAJmMRGIzgFtNZYVHRQqTClDAeyeRLqUIHzHmNDZoirLJniwyGHiqkGHkmeOtDwYKXZCOj"
DMHQoNfILaKkFOBjEtGuKnuYuXXGOlAboFpuyqvfziNHDabwzXHBZlDekCltezZnKQNpybRydZKraDI102 = 536
k100 = "DhgDNVUEmFFAxVZpFEZEGSbByelEOCahdDgmVDmTisDQutqpLDvjniNIUsUvCsxpmLVnFwqEKazxaBO"
IIIIlIlIIlIIIIlIlIIlIIIIIIIlIlIlIIllIIllIllIlllIIlIllIIllllllllIIIllllIIllIIllllIlllIIlIIlIlIllllI = "qXZCBilXXgVkCehxydYPKZbeWmtdyUmzzGIhMixocfIMfnGfmiQIlqgKEBlvXbBWnfqvBdjTDlNsZGA"
AaaAAAaAAaaAAAAAaAAaaaAaAAaAaAAAaaAAaaAAAaAaAAaAaAaaAAAaAaaaaaaaAAAaAAAaAAAaaaaaaaaAaAaAAaAaaaaa = "TOArYkqhtbPONNxDGtafkqEDwZyXibWziqbOenTJrLQlsAkUpZnIDsSkpUgtbHUunfafsGIVUtDRnzb"
B1637589809947819794 = 60
x92 = "JkDipWhiFfqqXsThiGkHJmZiIcxtSbCHWEpnXyuBcHqDUWTzKdofYNMlTgBrtumKiTfgkjinGUfhHCm"
IIlIIlllllllIIlIllIIlIlIlIlIIlIIlIIIlIIlIIllIllIIIllIllIIIIlIIlllIlIIlIIllllllIIlIIlIIlIlI = "muhfaNpRdWrhndMAOdasWgqwKiMgusDyIBFGTLOLizaKPqeZeYRpNVpNhhLMvQAywTocWTZqOOUQSqT"
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = "xuFXtOQgtWUmSyRViJQJzwjUMzJnMHkRdWTKjDuqoBJEtSoTKOTzqaucxSOYjwzRCSAIFMFKIYqpMWb"
o86 = 353
t163758980994504984 = "etrZKonmgenEOeTyTdjsVMIDoaAcoZjDKTvNXkXRXiOpJJNgSSpUxXAMPlZoPqZwOztSHcIBWvaCUvJ"
h82 = "MhhXBdcWuyWvNPqgFyIVXsEqPOGHKRFwJaRyVIWegmzmcXimjYFYmScwrTHwCYxZnURkPAxyKLSfGOh"
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = "MKFaMCmOQuAxACDFvqfXweYZXYHDSYNggHhFFxDGlCUAKvmEHzVTMfTNmGXqufAuIkPJPvJzlDzAufV"
d78 = 251
x1637589809943651476 = "sAhoKjoxnOeHqEZDrIvwvWZnKEzCcDbpZODAfYsYqEortbaxzLQEGCfexbwZbZnKQFVNKUMCKGkolWZ"
IlIlllllIlIlIllllIllIlllIIlIIlIlIllIIlIlllIIlIIIIIIllllllIIIlllllIlllIIIIl = "VqMKSRXIXoBzckNzkjceRjuHTEGQKgifWkOSaYhfaSEqyoGgLcZhUbjdALpzPVUmLsOgODkHZCkRGBF"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 403
z163758980994139270 = 336
aAaAAaaAaaAAAAAaaAAaAaAAAaaaAAaAaaAaAAAAaAAAAaaAAAaAAAAaAaAaaAaaAaAA = "HAooVsGuMIukEnsLNXWGjlYFkplbvtEpSOJfZJSdeHPrEpbNJhqeUArbJcoZDOHzdCAQqfTTJZaAnNS"
NRDqLAvEOZABQSTParqCPqyxevkdfyxusxjaXANXnEaIPHngUHnwmpqQgEjnMCgfDetqHAJfYnQuZmd66 = 478
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = "OktkrArKQJcoVwlQadgSWHqTVVgmWstlZohcSnVHXTlsYVgtLlcpQCVQbPLFSFZnRlChSmsrfCChWah"
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = 751
n1637589809934886560 = 290
E1637589809934811858 = 799
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = "AiaAjhCjMdqyoBvsfQcAUouwhIyyqZjwhnfPOpLVJuxFKBrschAQAyxzKPYIaxdJZSxbhtNCWZyRDVc"
d54 = 248
n1637589809934222752 = 535
llIIlIIllllIIllIlllIIlIIlIlllIIlIlIIlIlIIlIllIIIIl = 240
P1637589809933808848 = 705
AaaaAAaAaaaaAAaAaaaAAAAaAaaAaAaaAaAaAAaaAAaaAA = 64
AaAAaAaAaaaaaaAAaaAAaAAaAaAaaaaAaAaAAaAaAaaA = 452
Y1637589809932871842 = "PnwfRFHdVqCgQaRbigjLiKlDZfcHcomgpyubajYXEYTGodYLBAWhWuhFCSvrccJJMGdqfgOPcRJnzJz"
lIllIllIlllllIlIlllIllIIIIIlIllIlllIIllI = 415
AAAaaAAAAAaAAaAaAaaAAaAaaAaaaAaaAaAAaA = "BdHOJpoDNSbfmeJGyVzxobRjFNtiuuXkWLTmFqXEDClLIfLOLTZMOHjtIAfZCVBukWNmkVRMUXSADvC"
s1637589809929742836 = "rBtUodCXljaOTFmOFwhhrNhrcylZjjtgefGPQWjIFluMpppXRETMEHfIJzwXUnHviGfQlhuSHFCiZzN"
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = "oGumqhEZfpZfcrZhffOsbFhebofgZchCnqvNADgAzDdwiFhajlPFKUdXbOcHttLjHDJfrNUdCPDRZwN"
llllIlIIIIIIlIlIlIlllllIIllIllll = 274
mYBSigRRvkfdCDLzKmIPnsRXSZaIbaqLoUcCSiJbPOOskfEwfIAKsTAOwxnnsXomRTRPdLRYIPBnClA30 = "QeMBcDEEpTBGSjuGajGzvTxpHgFydFgmvvmFbVVkTTjfTcFzljCFAmEbMnVyvzzOJfYZkteOaoHEzbK"
g1637589809923928728 = "zZorcDAAmLIphfHAtErTjUbBWIQWWSgkVGaBUfgqJyGadDakoXWozRiswdxZPhKlpKpCGLSlwWdYcdX"
a26 = "PdJPCnduOgvZiAkHSEAGQsBSgccVjrOwiYVMBQFfIcqVaKKAewCWAdAdiVgoXwjThlFjVDNkHVDOrfj"
aAAaaAaaAAaAaAaAAAAaAaaa = 909
mjdnGkwflZDUyXXWuCUPexGOitivPrEmYFWBQVGRhoTZiDbmLsyuRCdyxwNvUIKqiueyQvtPPlEKLOu22 = 416
WWWWWWWWWWWWWWWWWWWW = "fquOyKPteggiHZbGRyULdCLwJPyhOGfkalBqyQRneedaSIhvpdCUfKbcogmHmeKoHfqyiDjgyMCpwav"
W163758980992184718 = 307
VJfAomcdunpkvtOjtezxNIgVbqDuBvKJUnVzYucKqIJLDNAyOdxFNozgBgJbyzkPTzVdbZtmuUaYfSE16 = "aFFIKBbAuiHVDtSSnititjWhlpQzXlhDTDFnBDIcOLraLeeHvKgkxybqCbgpWITOJKsLkZCwFCDtIxB"
aAaaAAaAAaAAAa = 639
aaAaaaaaaaaA = 229
I10 = 174
xxxxxxxx = 312
aAaAAa = "LKHWpWAbHHgDSRHoSzuTRjTGNcsnMxERINayNQvvuSLOAPxgJJZqWWRzOlrNWVhmXrFPjwWSxRNaUrv"
IIII = 359
F163758980991583542 = 377

#!/usr/bin/env python3

import os
import sys
import time

def lowprint(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(2.0/90)

e1 = ('''\033[1;33;40m
 ___________________________
|                             |
|                             | 
|           1 RUN             |
|           2 SETUP           |
|           4 CR              |
|           5 UPDATE          |
|          99 EXIT            |
|                             |
|_____________________________|

''')

YY = ('''\033[1;33;40m
 ___________________________
|                             |
|                             | 
|       1 SETUP TERMUX        |
|       2 SETUP SHELL         |
|       3 SETUP UBUNTU        |
|       4 SETUP KALI LINUX    |
|      99 EXIT                |
|                             |
|_____________________________|

''')

GGG=('''\033[0;32m
╦═╗ ╦╦ ╦╔═╗╔═╗╦╔═╦ ╦╔═╗╦ ╦
╠╦╝ ║╠═╣╠═╣║  ╠╩╗╚╦╝║ ║║ ║
╩╚═╚╝╩ ╩╩ ╩╚═╝╩ ╩ ╩ ╚═╝╚═╝ o
=================================
Project จัดทำโดย Sakol Thaneerat ได้ดัดเเปลง ทำเพื่อเป็น Tool ในการใช่ DIRB ได้ง่ายขึ้น 
''')

lllI=("______________________________________________________")

os.system("clear")
lowprint(e1)
XXXXX = input("number : ")
if XXXXX == "1":
    os.system("clear")
    s163758980987270337 = input("link : ")
    llIIllII = input("name-word-list (1.txt): ")
    os.system("dirb  %s  -AaaaAAAAAAaAAaAaa  %s " %(s163758980987270337, llIIllII))    
if XXXXX == "2":
    os.system("clear")
    lowprint(YY)
    R1637589809891704610 = input("setup : ")
    if R1637589809891704610 == "1":
        print("termux")
        os.system("clear")
        os.system("pkg install dirb")
        os.system("apt install dirb")
        os.system("clear")
        time.sleep(2.0)
        os.system("python3 run.py")
    if R1637589809891704610 == "2":
        print("shell")
        os.system("sudo apt install dirb")
        os.system("clear")
        time.sleep(2.0)
        os.system("python3 run.py")
    if R1637589809891704610 == "3":
        print("ubuntu")
        os.system("sudo apt install dirb")
        os.system("clear")
        time.sleep(2.0)
        os.system("python3 run.py")
    if R1637589809891704610 == "4":
        print("kali")
        print("kali not setup")
        os.system("clear")
        time.sleep(2.0)
        os.system("python3 run.py")
    if R1637589809891704610 == "99":
        print("exit")
        os.system("clear")
        time.sleep(2.0)
        os.system("exit")
if XXXXX == "4":
    os.system("clear")
    lowprint(GGG)
    lowprint(lllI)
    time.sleep(1.0)
    AaaaAAAAAAaAAaAaa = input("Enter...: ")
    os.system("python3 run.py")
if XXXXX == "5":
    os.system("clear")
    os.system("git pull https://github.com/sakol289/dirb/")
    os.system("python3 run.py")
if XXXXX == "99":
    os.system("exit")
# else:
#     os.system("python3 run.py")
I = "xbKqfBGgOCwSlbAsWViTxCaPeamBSYhQbBHOvawizjCllvoLDOGwvmNuiwwoFFsExHsOUAIYIctkamW"
HHH = 306
U163758980991663315 = "BoRjtIkEgotxtrFuHzpJnpfbqmJQFXaKJvzRdoGqeaMJcttCFzfIIstafuAaCPbeEIteEjsrRvSaxZH"
q7 = 591
B163758980991868339 = 663
X11 = 792
aAAaaaaAaaaaa = 414
C15 = "FLXahNfzkpvxZUnUNrqXYBKUKxkjCXInldBUfXWSDohkqbOqyIWpULakSiHVwqHdvjvqPKTbYWYWDpg"
y17 = "JEJSaurUulCKCGOyHVhxRmWfbvDyoMPMSZzsQEsbfifSNLSnHZSkreteayxoVUcpKYzYwrCWWctShys"
tFMKRpaZsBIvTmVEjfpOXBSDtPtIFmsUIZSiQQyfOcsBFozwOjVPNUrPfbmBNJWKdITnlcCaYNWBKsh19 = 268
wwwwwwwwwwwwwwwwwwwww = 201
lIIIIIIllllllIlllIIIIIl = 184
C1637589809923411125 = "QLDcTmlaYKaXfXVWieEpGkSVdAWPPVtnnUwhNRNECkyMlighcTuzMFhBQmUYkwxzwOrhMrXFRfCyUUS"
OOOOOOOOOOOOOOOOOOOOOOOOOOO = "FqNUFlMUJdRGtFxgfVVZiXOKXHCkGNeGsAGwVLgokTVlULEwxlffEPDdxgtseVJHWfZhNieiMOvEMmt"
rDPyuQQFofYWbhiKyfzIrVcaMssRcgNKlaALLRzQhfirxOuMKqxnSMsJNUiCwLkcSOewOXMzFopLiSW29 = "eukUSRvVHAFawWTPsANihBlXQaRMbPtheyuhlllpKbkHzDSPNTalfQlojgdylpmzKDCtBMDwIFWmXWL"
k31 = "nWowzIBPcwPdUzsHJSaPrHClDjGePtQPSUgPeiLbMJpDksXHYxlbMmkdaVaTTCiRjTcpWWFXuiCoout"
AaaAaaaaAAAAAAaAAaaaAAAaaAaaAAAaA = "UaEpHASREfRrrYjAKbEfBMMsJSechpXYvxFYWPtuhUcxxisfKjXPUzgTNewndhUfkouadeulRnsrjeu"
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = "lUqdteDsvLeobMIKripbTPRGukeYbXOHFweCJGyQQWffakSeQEYSERJrjqnLRpfuqKmWvDHNYkAmyqi"
cIUZKwJMVkdVjPvvjFBNjqFzwFmmfGpPIWcplQFSZsTVkGLTeDefOsHGmihrNTPykvRFcvJocDVQOVd37 = "IJCCwKZWZsDjcUvehjhvqSeLuftadAyTNtCLXSjbANsISuXXthoJDzMMqwDyUwlXvfXkCjaMeJKpJhe"
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn = "UpqMjPeGKiagpCrZTsbTYwIXghvZWYjYwKWSMqMcXOIUeZZGCPFJiilaGOeWpLbndlRuxuPlODQdDgP"
lIIlIIlIIIIlllIlIlIIllIlIIIllIlIllllllIII = "cwfDkZGgNHxVQMJYZQrSrLwxOwauBQUCbOGOsiwwfySBwSMVpQBsetVSpoTLVrypuZbuvlbKJNAHhpQ"
llIllIIlIIlIllIIlIlllIIIIlIlllIlllIllIIIIIl = "yuCLDGNDwjiYvWyMUOTBtyFGxJqrICIQDqhhcktkDpFfaiLsUtAQFgISnPtCykBXPbVSQteFJgTeAmj"
p163758980993338845 = "QCODfZHhXyVEYFAyOYtZkbhqmjuvyfLPjThSBoCrUoDwPNYbuWYlrROXtffBbPmFyGlOsmiPdZHNhzV"
CYuVgkTnCehBaoNRhnPYHQXqRgEfkFjBCGcsMzBYZqvbCNQansaZTHrHzeZDAcKAnNQzrQmHFYzjdnP47 = "XvetxSiQPGKGIcZUvmhPkIwCTtkxvFPNfGSNqCCNhlgCMyahBUpMFucuJzOiLBlQQtDWSJMpWMnYFaJ"
AaAaaAAaAAaaaAaAaaAaaaAAAaaAaAAAAaaaaAAaaAAaAaAAa = "OwiwGCHDbiYHnlnFtMQIFLwRwYCkykBxajsapXMHFDvmHVeXhVAukpfHfwSzfBYAvDIaIhsmXeWoAtu"
M51 = 576
t1637589809934384353 = "AHPgNGibocnqIOIKmoSVApjBihXCaYtOYkmLGOmhfWTbIdUWXBvEyTmgbtzAmJJXBeKrVEYfRUxMfTM"
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "sNotzwGdXGuZcQEZLLwfOlqrOBHTZMjIIcqRsjLLxOLYvYIiUfetJfYGGdlkUdtUxEEhUKNRlLRmuyM"
lllIlIIllIlllIlllIIIIlIIIlIlllIIIllllIIIIlIIlllllllllIIlI = 701
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = 333
i1637589809935119261 = "JsSCDuMiwcjpaWJEZkUjYdhWWeHqLxbRubsxDBttvyNvmfmGnqkwcwTbdjlKDJcMsXLcIonEbHNVhDG"
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = 711
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = "QXcYSiZVzhRYnZHXyZYDzzwOPKxeeIhMdPJBWHQhmANzpiEhVBDDfYfslTNkkcGqkcURIjjYwreuFaH"
IIIIIIIllIIIlIlIlIlIlIIllllIlIIlIlIIIlIIIllllIllIIlllIllIIIIlIllIIl = 162
aaaaaaaaaaaAAaAaAaaaAAaaaAaaAaAaAaaAaaAAAAaAAAAAAaAaAAAaAaAAAAaaAaAaa = 651
ZkCpKBUKxVAZMxISskEnXbTqoVQDWiIJcDMiFNSWbyYZcaWoibXOnVXysSCQKsVCoYftPwpWRUhmoyg71 = 514
Z1637589809941620873 = 455
f1637589809942294675 = "CeTzWQuciyZonuNAyNbGGzVWVOiPSSndyJhvMyCJZUVyCvDezwdoVZPYdjMNwPFZqdKOJmIsYCzuWgz"
p163758980994391377 = "YIYRIDfZakpKvGNADaXJVoTXoBwHXhEJXQKEkUzRGRUKffJcNqXQmbTcIHwUwBosGEyfmdQQxiYNUsh"
S79 = 331
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 399
v1637589809944750383 = "VEYThTiqeUxKrqhsltLpkKjBTRLiIoltBWBZnyOSRcAWfopEerWOPtonbvmTCRcIhBIjplKJQlBeZus"
ynAJCVTBPyPQvNxgyQbKwZtCKIjJybBxDrrgYjlIbwgKfYApCjMYFEPyQKHHYcAhlSocYwxkHuTuZGK85 = "WJBVEkAJXfFXjVfjEAPZyikIBwbGvwfVgjVRJGPwAPCfTTZDqzOtcqKSdPyocvXEKVWNegcUtBKxscX"
g1637589809945339287 = 26
IllIIlIllllIIIIlIIlllIIlllllIIlllIllllIIlllllIlllllIIlllllIIIlIlIlllIllllllIllllIllIlIlIl = "ustSyGvlDJXlFLXGImtwLMqjvdYsanHafWPyUtSWXWVNZadEmnjdBRKLRlJXYaBebGyXLunrVLZoUyo"
u1637589809947144791 = "pKFrfiUKhukPWgSEgmRahptKpDMvOsGIxoYZEbYfChhuaBPjnObTIhPVTgegbqjYItPqBaYEsmCpkkz"
AAaaAAAAaAaAaAaAAAAAAaaaaaAaaaAaAaaaAaAaAAaAAaAAaaaAAaAaAAAaaaAAAaaaaAaaaAaAaAaaaAAaAAaaAaAaa = "VbjTNNPbeOymhwAocBqZGmpEdpkAtUMxUdLwhBHwrvsyDqHSpzwWYliuSNoaNcKNTkFRUXqFwVyOZGz"
Q95 = 653
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = 489
KTUtGXEWMGLzIjfClDQOJAbqJAFdgVvyCpraSWsJexOIMzTYGEDKbSaasAoosbqihXIMhqoFjUxMlNH99 = "ispHRDlpCOXprXaBgDNOPbPPlZYhrIXIgpWweVvNqDuxPvmHnGdfbJXlJpCUYujjqGbClDsPIpJPbFA"
IllIllIIllIlIIIlIlllIlllIIIllIIIIIIlllIIIIlIIIlIIlIIllllIIIIlIllIIllIIIIllIlIlIlllIIIIIIlIlIIlIlIIIIl = "VgFMWTNCwMqAcAzvMNeZFEuMgjFhOyGXIBXOLZHyeJcGXMGUbdCwDWTqCjRdllUvaRVBVzXFPUSGZFI"
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk = 312
lIlIlIIlIIIlllIlIIIlllIIlllllIIllIlllIIllIllllIIllllIlIIllIllllIlllIIIlIIIlIIIllllIIIllllllIlIIlIlIIllllI = "JaQvqrBafyGeTjIZQJuTlWLKQNYSjdSYMEkxZDAtVFyzLxLJcQBdYhFtOVHYTizVjqmWocOcfoLQyXn"
OApUrZzTIzleIMvQWouoSuAtINICychhUcZQJeFrecjbwCgujFRdpbpQEfsECZcoRIUEvDQdIzszhCl107 = 632
g109 = 245
UpTXuKEyKTfYJKoPJWpcuHnwauFTksYGyDZZKlnyispYVZFtaFuldZstBoeQjKrsErrJPNiOrZPgtUq111 = 129
L16375898099616196113 = 292
N1637589809962975115 = "rEbeGeYPuoVYqKQSBmwRUeDBzdrSMyLuzPfXzulrTlavYcOhcsyQZItjUMkXZMmCYkRrRQswKgixvYA"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = "BQwdqoKZHxEitpMzxLTeWzCgaGKviWmoGigzaedlYCCqmheULwwisshBtldOPtEmYbKiyubuYCMeknN"
w16375898099673321119 = "HvmqkSsYQbWVCFgGSMVALpOLkzojYBjfzHaMPsdTTbBieEpLMjiMVggZypYNhrWWCdTXKmfvijBoPUm"
IIIlIlIllIIlIIlllIllIllIlllIIIIllIlIIlllllIlllllIIIIIIlIlIlIlIlIIIIIllIlIlllIlIIIlIIllIllllIIIIIIllIIlIIllIlIIlIIlIIlIlll = "UhbOEAMUXEvRDgSrxXsihvZATKYmIUmrUOUcRywULczbCiLATgTipIpvXIJQCkJnAATGSTybfmkUbgt"
lIllIllllIllIllIllIlIIIIlIIIIIIlllIIlIIllIlllIIlIllIIIIllIIllIlIlIlllllIlllIIIllIlIIllIlllllIIlIIIIlllIllllIlIllIlIIlllllll = 802
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = "fHeGcmrzBZPsBVJZadLjFKCcXZSYdwwJZERRhwHnuswhJDZwpTxREdKYNkkbSqlZgTQcmoAHWKFINPb"
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 360
d16375898099734566129 = 670
rPZMuEyKBseYkSPnZPICkExxkqAsnpLxKRoJHkAhojLsoEdrCFZEgLMSdrFMKxIzkbHCFNMhkpHrCTb131 = 566
rHkuQeoMavQMWqRGmeYNiYkGKMDkFVMQlJiAUdGdbiPKGJoTcpFEZyhOjcyfhYdSoeVRoPZMapvQPWe133 = 664
n16375898099908655135 = 782
YQbzzFSGNHOWSmrOBxmtKSZMgISzMlxULRJidWvcndsYvaQsSGNdfYZrAjjoBtYQXXRmdqyQuxbgfAo137 = 554
zQIFCPTJGoCIQwhnoBqdgpLBdOfuaQoIycjXmMHpjnzyoUCMgRDjMWNbLHNZmGRdLKCBNTYbUIIDPtS139 = "iSAEyzEdTiGewoFSoIXGDITYhmnykaxstGOTdhWUBticqXpUYlMqnBlXPfnljRDPvCSqIdMwsZHiLRZ"
IlIIIIlIIIIllllIIIlIlIlIlIIllIllIllIllIlIIlIIlllIlIllllIlIlllllllIllIIllIlIIIllIIlIIIIIlIIllllIIlIlIlIlIIIlIlIIllIIllllIIllIIIIlIlIlIIIllllll = "NkvjqRjGwCLziaRkSexCptifUyOrcluBIABwXTjrnTQVgVsoEGZGQEBgVwSOwVLXtMSiJjTnOEbzohG"
lllIllIIIIllllIIIlIlIIlIIlllIlIllIIIlllIIlIIIllllIllIIlIIIIlIlIIllIIIIIIIIIIIlIllIlIllIlIIIlIIIIlIIlIlIIlIIllIlIlIIlIIIIlIlIIIllIllIIlllllIIIll = "GVaVnZYKurCzBHjrBWjRCJiaYSWbkiMupLzbHSLOOqwQiEQjhWzcAKfPBNbnNXjRlduJvqjKbHvcyuM"
IllllIIlIIllllIIIlllllIIIIlIIlIlIlIlIIIllllllIIIIIIIIIlIIlllllllllllIllIIIlIlIIllIlIlIlllIIIIIlIlIlIIIlIIIIIIllIllIIlllIllIlIlIIIlIIIIIlIIIlIIIlI = "wFCxoKpRYFHiYUHYrGAABldBzeAyHrREFOIoEyFJqFpTuLDtRSggYiPbKHdSDAOulCcvreNnYWJzMFP"
lIIllIIIllIlIIlIIIIlIlIllllIlllIlIIIIIlIIlIlIlllIIllIllIlllllIllIllllIlIIllllIlllllllIllllIllllIIlIlllIIIIIIlIIlIIIlIIllIllIIIllllIIIlllIIIllIIIIIl = 659
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = 541
T16375898100078845151 = "fBmMARFgdzKFYlVHBbGoLgDANihRMgvdwdBfeZMAKqFUEZmiRIFoqYwQwrncfrXNybvQqnChrXxxyMk"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = 151
lllIlIllllIIlIlIIllllIIlIIIIIlllIIlIIIIlIllIIllIlIIllIlllIIIllIIllIIIlllllllIIIllIIlIlIllIIllIlIlIlllIllIlIlIIlllIIlIlIIlIIIlllIlllIllIlIIllIIllllIIIIIllII = 598
aexCAthQiSTrAzKqbIgNiwbvfCUNaShmDhnLWtvoosuogmWkgymvQCfKamMjazBeqKUCzxtXkLjrdzY157 = "gnZGszLhKYJnLMQitrSCVEiHhuFiFhceOEgGGYBkLdieLPPhQeoAmsOGVYzqWTwQErmijgclNQLtNvu"
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM = "coydKgsPrCehctMSNkxblwuGiXOFnKDNcexyWuxWxYVLtiMWekJcRmDQYRnWHTlCqoAcgbXWNusQJmV"
C161 = "QYhuNIeheZaXdpccgJsGdxsgvfgGrpziVmqIHdALlEfqtCkgnZJFLFRRJmRncPiKNROQiIFKaVxdapI"
ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = "lOyTLBrPmIabBmCkZCFaQLcxwBCAGGhOuSfKvZNwVHSnuRIPnvIgMyrsReTFVWkcFYghkNTorVAYDym"
y1637589810013421165 = 461
AAaAAAAAAAaAaaAAAaaAaaAaAAAaaaAaAAaaAaaaaaAaAaAaAaAaaAaAaAaaaaaAAaAAaAaaAaAaAAaAaaaAaAAAaAaaAAAaaaaAAaaaaAAaaAAaaAAAAAaaaAaAaaAaaaaaAAaaAaAAAaaAAaaAaAaAaAaaAaAAAAAAaaa = "IoVOydutIBmyIBDsMMXzpoGokfAKMIIIwvQrqKvULZXVjRPkePISoJTneTBWsLipZggsflMrFVoGYRP"
aAaaaAAAAaaaAaaaAAAAaAaaAaaaaaAAaaaaAaAaAAaAaAaaAaAAaaAaaaaaaAAAAAAAAAaaaAAAaAAAAaAAAaAaAAaaaaAAAAaAaaAAaaaaaAAAAaaaAaAAaaAAaAaaaAAAAAaaAaAAaAAaaAAAaAAaAAAaaaaaaaaAAaaAA = "LMkUeeenUGUBatqWIDCSvsuDftnHzQidmoIlAeGjYrxgGFetzRryqLAUCXYGslmjxwoRIgDVPbEWuQS"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 719
NVMsEsrHcQsDVgFIjZtnadBJelSbUblVaZREJQvgQyFyoWhRXRPOKOjOXRAGzTTvUyLDoZMRdRNQkJb173 = 793
t16375898100146434175 = 203
AAaAAAAAaaaAAaAaaAAaAAaAAAAaaaAAaAaAAAaaAAAaaaaaaAaaAaAaaAaAaAaaaAaaAaaaAaaAAaAAAAAaAaaaAAaAAaAAaaaAAAaaaAaaAAAAaaaaAaaAaaAAaaAAAAaaAAAaaaaAAaAaAaAAAAaaaAAAAaaaaaaaaaAAaAAaAaaAA = "AsOytzOuHiAbuCnxyKYeLcVVEuJvEXwmQlGniEhlabOZorCrrdLhhyOBhZXjdpCoATgOAnBWIRZeRVc"
b16375898100155523179 = "fLRiLwNctZdCXrsrysooFqvaTonvItQWCOPupxGIuvKxphmYykwDknFBoMjIWlMLDuZNXWHzAIIVDyC"
jjNCDTUNiTpMYEgMdtktYbdwuiomoFokIufmgVfRWKtHEOWkQxLZQlroZYNovtqYBQywsCpSqKBPRhk181 = 284
J183 = 524
lIIllIlIIllllIlIIlIllIIIIllIIIIIIlIllIIlIlIIllIIIlIlIlIlIIlIIIlIIllIIllIIlllIllIllllIIlIIIIIIIlIIIIlIlIIIIllllllIIIIIIIllIlIIIlIlIlIIllIlIlIIIlIIllIIIlIIlllIIlIlIlIlllIIllIIIlllIllIllll = 326
U187 = "zKzhxGfLPhyTpOgMonflrPGPAiIGWVkDgKKyzDtbjFaibcXOySapNzhLSWAafPENKjPGypMcREBdVrJ"
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG = "ExRtkcUjoxeZUqowsYyisVuVBCLyKrFwnJiuvUFNJvLpZbGhREhLBAwMIDIKRnhsbPJrnuMeoLRicMO"
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = 519
E16375898100372674193 = "YoxWqdgvBQMtnmRlclYLYnOJJkpIQRaidaXDxNKhRECjVHLrwSPuhqRZrkoHjVmQQTkkbebHgXJCnaW"
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 361
N16375898100380874197 = 604
dInSAEcWkGubRxDIVIfeCTDwUwiJOeryZPQujfoCogRTDMgWDlkGVxBPVzrHdLadgeMqBvLdcXiQwMy199 = 610
ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = 684
AvAPwteNBtwfYtWhsseIwnEpGtoEFVmxDYwveqNrhOLglogaUpBYXkkWtcIploayFksVuPJppDiwDKC203 = 312
llIIIIlllIlIlIllIIlIIIIIIIIIIllIllllIIIlIIllIIllIIIIlIlllllIlIIlIlIllIllIlIIIllIlIIlllIIllllIllIllIllIlIlllIlllIIIIIlIlIIllIIlIllllllllIIllllIlIIIllllIIIIlIlllllllIIlIlllIlIIIlllIIlllIIlIIlIllIIllIllIIlIlI = "ECwgtIoThIDfzfIqAnquRuEAxnMPMPeqoeqEkROrvGMzXBXkhVdlChKZwqTIKpfKGctDsWxUToVRsbj"
aAaAaaAaaaAaaAaAAaAaAaAAaAaAaaAaaAaAAaAAaAAaaAaAaaaAAAaaaaAAaAaAAaaaAAaaAaAaAaaaAaaaAaAAaaaAaAaAAaAAaaAaAaAAaaaaAAAaAAaaaAAaaAaAAaaaaaAAAAAaAAAaAAAAAAAaAaAAaaAAAaaaaaAaAaaaaAaAAaaAaAAaaAAaAAaaAaaAaAaAaaAaaAa = "vpfbWwNZkPTnzcuJcwDSNcKEOZWmWnrXhtYZWHbOyqsHrBMzGBWbeccAABlNXyEHnOaFryYyXiClSAw"
s163758981005921209 = "uvQYCIJpboDVaIggJJGixEjMnmdFgrmzRvCIEBbLPKjltpxjnOsIchIrylNRkmKYPkJodqtsCSAhggH"
a16375898100597117211 = "AFVQeQcXiJMVinWhZlgtoDmCddUYyGELAKXdJlmuHtqkcGIXezkzCaWkDdDYywGVIbDVjapCCgOyfyD"
s16375898100598667213 = 563
F16375898100600863215 = 568
gGtHqqFMeYwaOTrqKyiYoxSJkLyJjuBVThnZFNGGPfRBqfxCQZRKGPFjplFErthZgJvrrrSOcDelXiW217 = 156
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj = 333
llIllllIlIlIIIIllIIIlIIIIIllIIIlIIIlIlIlllllIIlIIlIIlIlIIlllllllIllllIIIlIIlIllIllIIlllllllIIllIIIIlllllIlIIllIllIIlIllIIlllllllIIlllIlIlIlllIIIlIllllIlIIIllllIIIlIIIlIllIllIllIIllllIlIlIIllIlIIIIlllIlIIlllllllIllIIIIllIl = 239
AaaAAAAAaaaAAaaaaAAaAaaAaaaAAAAAaaaAaaAAAAaAaaaAaaAaaaAAaAAaaaaAaAaAAaAAAaAAaAaAAaaaAaaAAAAAaAaaAaAaaAaaAaaaaaAaAAaaaAAaAAAaAAAAAaAAaaaaAaaaaAaAAAaAAaaaaaaaAAaaAAaAAaaAaAAAAaaAaAAAaAaaAAaAaaaAaAaAaAAAaAaAaaAaaAaaAaAaAaAAAaA = 747
aaAAaaAaAaaaaAaaaaAAaAaaaaAAaAAAAAAAAaAaAAAaaAaAAAAaAaAaAaAaaAAaAaaaaAaAaAaAaaAaAaaaAaaaaaaaAAaAAAaaAAAaAaAaaaAAaAAAaaaaAAaAaaAaAaAAAaaaAAaAaAAaAaaaAAAAAAAAAaaaaaAAAaaaAaaAAAaAaAaaAaAAAAAaAaaaaAAaaAAaAaaAAAAaAaaaAaaaAAAAaAaaa = "thirEITjoiEYHnqZFxrJTQKiAUilQOXqtbyUHJeATMznPEpVBsdXVQvEihUFCDtyyEGllkOLpCuOIOV"
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = 556
aAAaAAaAaAaAaaAAaaAAAAaaAAaAaaAAaAAaAAAaAaaAaaaaaaaAaAAAaAaAAAAaaaAAAaAAAaAaAaAAaaaaaAAAaAaAAaAaaAAaAaAaAaAaaaAAaaaAaaAAaaAaAAAaaaaaAaAAAaAaAaaaAAAaAAAaAAaAAaAaaaaaaaaAAaaaAAAAaAAaaaaAaAaAaAaaaaAAaAAAAaAaAAAAAAaAAaaaaAaAAAAAAaaAA = 915
MorBOPzhCPfkloqUaHayctDWorXkUgSihdqMgVlAihGfNcMWECZtzccoPFxaFwqbuXFNGNnqXyyRPnE231 = "qjxZLRalHWAijqMRMJHWRWPVDUYGbVGAHikmAqgXSXbqgQCNACXIpJggphvXTxGjBEjyNRjubwllanB"
D233 = "blcbiIMkPgFpCyLIFgMEkHWHTkkseMApJEwspCONvxLWqRaKsHjIDIQQBZAXpmJCZglJWfMhjHKbHfG"
n1637589810070842235 = 313
T237 = "tIfseBxPZczFRYUDrMXDtRBHpOdSaciPlUTKhTekssBDceXgTyCCvqOWKILuEPOIkiykAWhQIiTZDgH"
k239 = "UCQYJYhJlGYVLXWRfUPqBpDEjZilkJAvFBcxKTeLRzeWTYknzJqSdRPXAVjUPHEJgEsGCmzIbsJimGS"
w1637589810084502241 = "UnigqzrkWbFnwIDVzXETzUEwWUjjbmDGckGXyyoaQvYZWyTEDlZIvujrknwypmwaEpYhftRnvVBsJpX"
C243 = 220
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 238
llIIllllllIlllIlIIIIlIllIIllIlllIIllIIlIIlIIIIllIlIllllIIlIIlllIIllllIIlIllIlIIllllIlllIlIIIlIIIIIIIIlllIIlIlIllIlIIlIIlIIllIllIIIllIlllIllIIlIlIIllIIlIIIllIIllIllIIllIllIIIlllIlIIIIIIllIlIIlIIIIIIllllIlIlIIllIlIIlIIllIllIIIlIIlIIlIIlIIllllllIIlIl = 107
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 891
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV = "swivwtkUsxQLbYdtxIGzGiOhdjdGINDajJIMuEGUxSJbRMbowCxaecElacPHEBfgUxjcUcBEZmQIaqV"
ttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt = "DnrrRiKolrthcenIuMFpAbJKMjhUzGMRTufXYvNVxoChvnPwclgWKVWfznSFmWpKeNIDXVJVvIrUcuc"
I255 = 650
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = "VJPLldaMiYyjpoBfYONMMAukljCOKSjpxwcjzaxCknXJSMxQRzIoOtKSFonERcuIIXDkwKVLvsPUpea"
IlIIllIIIllllllllIllllIllIllIlIIlllllIllIIIllIlIlllIlIlllIIIIlIIlIIIIllIIIlIllIlIIllIlIlIlIIlIlIIllIlllIllIlIIlIllIlIlllIIlllIIIIIlIIlllIIIIlIllllllllIIIlllIllllIIIlIllllIlIlIllllIlIIlllIlIlIlIIIlIllIlllIlllIIlllIIllllllllIlIIIIlllIIIIlIIIIllIlllIIlIlIllllIlI = "FIHHRaCCSBucRprNEUNuXZloJxAIcAQKVXRzLkDheUoFGpsMeNEqzhODjkiNyXAopkrNSjMDQdefFPC"
IIlllllIllllllIlllllIllIIIllllllIIlllIlIlIIIlIIIlllIIIIIllIIlIlllIIllllIIlIIlIlIlIllIIlllllllIlllIIlIlIlIIllllIIIIlIlIIllIIllIIIIIIlllllIlllIIlIlIlIllllIIllllIIIlllIlllIllllIIlIIlIllIlllIlIlIlIIlllllIllllIIIllIlIIllIIIIIlIIIIlIlllllIIIlIlIIIlIlIlIIlllIIIIIlIlII = 480
o263 = 315
EjTSBOFOVuTGrqJFOjekkwLGEcoreYJWVrowKrucwAUBWHPEOUwfwcvLRzgUgaYcYxUPHzRjfxcGehW265 = 563
hdDuXWClPMVzJVaUdIuSoIqdLnNzrhfgcRwiMaEWQQRZsGoHxHfMSxBCferokEmmQWaGwiuhPSjohSD267 = "GhBvyUgsIociIrbOfxhcSHxOvLClpAZNFTsEhHpkNxRxYbouecAuyZYfXypvntnLxmUAtHwaXUjVxPY"
aAaaAaaaAaaaAaaAAaAAaAAaAaaaaAaAAaAAAAaaAAaAAaAAaaaaAAAAaaaAAaaaaaaaaaaAAaaaaAAAaaaAAAAAAAAaAAaaaAaaaaAaAAaaaAAaAAAAaaAaAAAaAAAAAaaaaAAAAaaaAAaAaAAaAaaaAAAaAaaAaAAAaaaAaaAAAAAaaAAaAaaaAAAAAaaAaaaAaAAaaaAaaAaaaaaAaAAaaAAaAaaaaaaAAAAAAaAAaaaaAAaaAAaaaAAaAAAaaAaAaaaAaaaAa = "DjxGQbKkFgCcQJCTUhCRWcnuauiNebaGWBuIIiGQYBnaLTWADujFIjwEkJMFLgPCvKMcPAtWmrQvKLs"
f16375898101133933271 = "CduOihXKINKwaobmCkJGopXWsMAGySAMNTzYDxRQyAyWEfuZWfPsppaymMHduuwcbHjjoSReAKvvLwM"
G1637589810114299273 = "FNlygldFtXjbEjiEPDKIRzpQORqKHYeoOjMSpumsnhYvUIidzkwpqkeTRzNvBHwDOEyYIieEmtRzWWb"
E275 = "IbQvPSnwKiHdUONUXcdgvILpYnZhUDJdzRiyaABNNvLRSvCZeHmJOrUSMGHaOMRmLDWLXRsHbwFUiHP"
IIIIIIlIllllIIIlllIIlIlIlIIlIIlllIlllIlIIIIIllIIIIIllIllIIIIlIIllIIIIllllIIllIIIlllIIIIlllIIIIIllIIlIlIIIlIIllIIllIlIIllIIIIllIIIlIlllIlllllllIIlIlIllllIlIlllIIIlIIllllIIIIIlIIIllIllIlIlllIllIlIIllllIlIllllIlllIllIlIIlIllllIIlIllIlIIIlIlIIIlIllIlllIIIIllIIllIlIIlIllllIllIIIIll = 676
aAAAAaaaAAAaaaAAaaaAAaAAaaaAAAAAaaaaAaaaAAAaAaaaAAAAaAAAaaaAAAaAaaAaAaAAaAAaaaAaAaAAAAaAaaaaaaaaaaAaAAAAAaAAaAaAaaAaaaaaaaAAAaAAAAAAAaaAaaaaaaaaaAAaaaAaaaAAAAaAaaaaaAaAaaAAAAaAaaAAaaaAAAaAaAAaaaaAaAaaAaaaAAaaAaaaAaAaAAaaaaAAaaaaAaaaAAaAAAAAaAaAAaaAAAaaaaAAaAaaaaaAaaAaaAaAAaAAaAa = 552
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = "NEvdnCitSpSCaZZqMjddKGOBvnQgKaeZiZCZJtypJiIeJvgqHonyqwAymEgXXfbZJShdZcEXXbWetXx"
nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn = "BjZMZttwvQZEzsrKjpCxmtueiUGrOgQnqyFeSreqecWpDlUZicZjwVdjWKnhjWFooVjkUmBZtIlcOnG"
aAaAaaaAAaAaAAAAAaaaAaAaaaaAaaaAAAaAAAAAaAaAaaAaaAAaAAaAaaAAaAaAAaAAAaAaAaAaAAaAaaaaAaaaaaAAAaaaaaAaAaAAAaaaaaAAaAaaAAAaAAaAaAaAAAaAAaaaaAAAAAaaaAaaaaAaAAaAAAAaaaAaaaAaAAaaAaaAaAaaAAaAaaAaaaaAAAAaaaAaAaaaaAaaaAaAAaaaAAaAAAaAaAaAaAAAaaaAAaAAaAaaaaAaaaAaAAaaaAAAAaaAaAaAaaAaAAaaAAaaaaaaa = "WMVVopcWysLXkKGuhFYsJMKjUwpPOKNllNOcHhSpNgbOFcVcYuFNFSeYwdUhINerRTyFLVnnQCrYMjw"
IIIllllIlIIlllIlIlIIllIIIIlIlIIlIllIIIllIlIIIlllIllIllIllIllIlIIlIIIIIlllIlllIllllllllIllIIIIIIllllllIlIIllIIlIIllIIIlIlIIlllllIIIIIllIlIIIIIllIlllllIIIIllllIIIIlIlIlIlIlllIIlllllllIllIIIllllIIIIlIllIlIIIlIIlIllllIlllIllIIIlllIlIllIllllIIlIlllIIIlllIlIllllllIllllIllIllllIlIIllIIIIllIllI = "QUDewoUBLFFYXYslKOzRvWAEmKSZUkEBLiJTBXSSkvFJilvPnMYDEbwydlVqhcvHIOztIzHNOOMaeml"
AaAaaAAaaaaaaAAaaAAaAAAaAAaaAAaAAAAaAaAAAaaAAaAAaAAaaAaaaAaAAaaaAAAAAAaaAAAAaaaaaaAaaAAAaaaaAaAaAaAAAAAAAaAAaAAaaAAAAAAAAaAaaaAaaaaaaAaaAaaAAaAaAaaAAAAaaaAaaaAAAaaAaAaAAAaaAAaAaAaAaaaAAaaAaaAAAAaAAAAAaaAaaAaaAaaaaaAAaAaAAaAaAAaAAaAaAAAAAAaAaaAAAaaAaAAaAaaAaAAAAAAAAaAAAAAAAaAAAAAaaAAAAaaAA = "JmQYYbeQQEhSNgwvoJtVaxvGMXmJzYJnSjBwOQnHhilnOqogwyMGdoyTCYFFFQbvbzvvBUsctxxWvLb"
B291 = "QJXBlODNTEVcGJIvpjZtUsfXiuCOwreitNEIFlkaPZULfcvrnaKLUyQInqbpiYNfgaRfeuMpvNQJCwA"
RjyKDPctsRLiHXOTQDfDnIOBHGPLWpZklwyaTYwiiQdkTtQpVrVoohHQDXAYvtUqyKYzMpxhLYJnHaA293 = "MBeTANCZMNwQSQlvNpkuGPqqoLLftcdgTKeXPiLfsSVWNCBqBaePtYlZDWZKYhcrOAOELrIhVhJjyAY"
uNJJlkkJQpCNfYvQlkeVZvBygEYiPjYNEEeSkfRZEQKZAXisICjDwjEpAQurAhZWLVabfdfUsaCUeGr295 = "RTmjzPiMaJhDHzfrVAxKiHiGipOQduJDLztpiSwukpaCNCtnpOFzAlxhatRSQUqjnbMHEiKYFUungWO"
q297 = "dYJfNLGHbMgcXXGENrKxUanLutaxPUhMAdYpSPoYMAHuTTasVTnEfJhIKRKPjZLjuGxegWDYdVczlqG"
i299 = 259
lllIIIIIIllIlIlIlIlIllIIIlIllIIllIIllIlIIlIIIlIlIllIlIlIlIlIIIlllIlllIlllIIlllIIIIIIllllIIIlllIlIllIlIllIlIIlIllIIIIlIlllIIllIIIlIlllIllllllllIIIIlllIIlIIIIllIIIlIllllllIllIlIlllIIIIllIIIIIllIlIIlIlIIIIIllIIIlIIIllIlIlIIlIIIlIIIllIlIlIIlIllIlIIllllIlIIIlIlIIlllIlIIlllllIIlIIIlllIllIIIIIllIIlIllllIIII = "MnEVSLVqvzDLDdUSnQrJYKHZyuHdrTrrHWxXevHljHPsiIojUpkPHbONwTrkQApjSufkySIMVxnyiTM"
SsTtiWiDJRxKLGykDBytQvnduDYbZUKwmkGKhkFKGKeRbpNcHwHdtSuHZaGYrpbeuBnVOloArqDoCGP303 = "LhYGEuZPfNDpFhDyKQboIcVzdFlZXEpvhkRwCKheDviQmHJgxmlwirQXslbIUrbpmoaYOZpDlMZOeQm"
x1637589810156759305 = "cBbIQwaBIrZMiYsgetZkvrsRwYxeXDSLnsNqQfhrOxSGYdlOFGjquBiScDoJXtlZCKtcvPqPTEeaffn"
mloXijRgSqGgPoGKkmhvxrEkloqiPwRluIgnibLgtQnPgQkKQcglwEnFpXBSPSOcKlyMLcjlrrWDBeH307 = 86
pruYCFzMilOMYfIHDiAgKVaLUQIyULgLtaJFGUCjUbLYkexSyMhixgoszZVWFIrEbstxwmSLTgukWEX309 = 321
KEHAIgPNXYUhFnAVlznEbyZrLdRpXDtumFgbVhtBlnaGtoUkivqAAaXIpEAVjbvOewOYNoyfhLaqAjH311 = "ppBduxQWIkEPrDyOPjzXWKLTnnAKZJCPkfOsUdSFfiCJTQqZXQbdECyVGRcNzsvWNskoEDuTViKUIuP"
r313 = "XrqbhfUBKwylTSLfkNZEXJvwqzYGvguqvoCjxOtuMfhcElOSHXdnBctXYUUDSncsUhugGowMugIhHvO"
IIlIlIIIlIIlllllIIIllIIllIIlIlIIlIIlIIIlIlllIIlIlllIIIlIIIlllIlIIlIIIIlIlllllllllIIlIIIIIIIIlllllIIIlIllIllIlIllIlllIlllIIllllllIIllllIlIIlIIIllIlIIllIIlIIIlIlIIIlIIIllIIllIIlllIllIIIIIIIIIlllIIllIlIlIIIIIlllIIIIlIlIIlIllIIIIIllIllIIlIIllIIIIIIllIIIIIllIIllIIllIlIllIIlIIIIIlIlllIIIIIlIllllIllIIlllllIlllIlIIIIlllll = "DTRjORkYQstvDhEGxMvXEhmvNlvswwUjoTIlOoDDGELppRbiMIHIYpLSYkKkAqEvngUfEJZwstJmdRH"
aAAAAaAAaaAAaAAAAAaaaAAAaaAaaAaaAaAAaaAaaaAaAAAaAAaaAaaaaAAAaAaaAaAAaaaaaAaaAAAaaaAaaAaaAAaaAAaAaaaAAAaAAaaaAAAaaAaaAAAAaaaaAAAAAaAAAAAAAaAaAaAAAAaAAAaAAaaaAAAAAAAaaAAAAAaaaAaAAAAaaAAaAaAaaAaaaAAAaaAaaaaaaAAAaAaAaaaAaaaaaAaaaaaAAaAAAAAaaAaAAaaaAaAAaAaaaaaAAAAaAAaAaaaaAAaaaaaaaaAAAAAaAaaaaaaaAaaAAaAaAAAaAAAAaaaaAaaAa = 247
J319 = "njitynSTNpTljeWLBzZKhUiXatcYYPhMcFkWVAqGiyYqPCjGBhzjmYXVtgTIZQaqySPFOOryzVivdOJ"
aaAaAAAaaAAaAAAaaAAAAAAaaaAaaaaaAaaAAaAAAaAAaaaAAaAAAAaAaaaaaaaaAaAAAAAaaaaAAAAAAaaaaAaaAaAAAaAAaAAaAaAaAaaAAAAAAAAAAaAAAaaaAAaAAaAaAaaaAaaAaaaaAaaAaaaaAAAAAaaAAAaaaAaAAAaAaaaAaaAaAaaaaAaaaaaaaaAAAaAAaaAAAAAaAAaaaAAaaaAAAAaAAAaaaAaaAaAaAAAaAaAaaAaAAAAAAAAAaAAAAaAaaaAAAaaAaaAaAAaAaaaAaaaaAaaaAaAaaAAAAaAAAAAAAAaaAaaAAAAaA = "KjvKtCGZQSTbDCIAogGwvXKskQqrcHFQfqPDvqpHAbdQUfZdVpyqnnrhiWaFINCGFfSawhcdQsIflyv"
k1637589810176068323 = 246
LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL = 496
U16375898101776638327 = "ocAIItLbZWFaNwbwodRGGNIgjWMGbMwNamrEzKRtljZPtcZsSqhitMUUIfaRYqMsaqUHdNmodcpVCJN"
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc = 544
aAaaaaAaaaaaaAAaaaAaaAaaaAAAaaaAAaAaaaaAAAAAaaAaaAaAAAAAaAaaAAAAaAAaAAAaaaaaAaAAAAaAAaaaaaaAaaAaaaaAaaaaaAaaAAAAAAaAaAaaAAaAAaAAaAAaaaAaaaaaaaAAAAaAAAAaaAAaaaaAaAAAaAAaAAaAaaAAAaAaaAAaaaaaaAAAaAaAAAaaaaAAAaAaaaAaaAAaaaAaaAaaaaAAAaAaAaAaAaaaaAaaAAaaAaAAAAAAAAAaaaaAaAAaaaAAAAaaAaaaAaaaaAAAaaAaaAaAaaAAAaaAaAaAAaaaaAaAaaaAaaaaaaAAaaa = "BEwZzYYLELMtmlRfLicjLacAlpkPFECoPbioUfSeOkNeiUTHsRlbrFYzSbelFCvvRHkxMKWpCwCWGMV"
aaAAaAaaAaaAaaaAAaAAAAaAAaaaAaAAAAAAaAAaaAAaAaAAAAAAaAaAAaaaaaaaAAAaAaaaAaAaaaaAaAAAaaAaAaaaAAAAAaAaAaAaAaAAAAAAAAaaaaAaAaAaaAaaAaaaAAAAAAAaAAAAAaAAaaAaAAAaaAaaAaaaAaAaaAAaaAaAaaaaAAAAaAaAAAAAAaAAaAaAAAaAAAaaAaAaAaAaaAAaaaAaaaaaaaaaaAaaaAAaaAaaaaAAAaAAAAaAAaAAaaAaaAaAaaAaAAaaAaAaaaAaAAaaaAaAaAaAAAAAAAAaAaAaaaAAaaAaaaaAaaAAaAAAAAaAa = "hNSOUciABRrKhtpinOprSWMnkMxwSuQSgmlnbbwDjCJoPbdmNKrrarWJyhngVsZsgMbWLWGNlYMEkMq"
aaAaaaAAaaaaaAAaaAaaAAAaAAaAaaAAaaaaaAaAaaaaaAAaAAAaaAAaaaAaAAAaAaAaaAAAaAaaaaaAAaAAAAaAaAAAaaaaAAAaaaAAaAaAaaaAaaAaaaAAAaaAaAaaAAAAAaAaaaaaAAaAaaaaaAAAAAaAAaAAaaaAAAaAAaAAAAaAaAAAAAAaaaaAaAAaAaaAaAaaaAAAaaaAAAAAAAaaAAAaAaaAAaaAaAaaAAaAaAaaAaAaaAaAaAaaAAaaaAAaAaAAAAAAaAAAAAaAAAaaAAAAAAaaaaAAaaAaAaaAAAaaAaaaAaAAaAAaAaaAAAaAAAAAaAaAAAA = 413
AaAAaAAaaaaaAaAaAaAAAaAaAAAAAaaaAaaAAAAAAAaAaAAAaAAaaAAAaaaaAaAaaAAAAAaaAAaAaaAAaAAAAAaaaAAaaaaaaaAaaaAAAAaAAaaaAaaaaAAaAAAaaaAAAAAAaaAAaAAAaaAaAaaaAAaaaaAaAAAaaAaAaAAAaAaaAAAaAAaAAaAaaaaaAaAAaaAaAAaAaAaaAAAAAAaAAaaAAaAAAAaaaAaAAaaaaaaAAaAaaAAaAAAaAaAaaaAAaaAAaAAaAAAaaAAAAaaAaAaAaAAAaAaaaaaAaAaaAaAaAAAaAAAAaAAaAaaAAAaaAaaaAAaAAAAAaaAAA = 224
toNoDNOcAFRzlJIisRNHMyJIuQCcHDcDevaZxbnwOIwKNmTevpSuWiXjgvapXCsiEyBbJsFTHKXwnCC339 = "dcxrBzTicQBFqqPSfYLaEKvrnruvvZMQHVVCtStfrQFymzfdgYQWvnGWMkBtvghSFALVhGeyWYQrKjO"
umoTKkwRNtSqOCIneGFUUgfogvGPflkdqIXzNwFNUzrodpOneguSBWyrdpNRhUvQImADtXUcTcmcRgI341 = "WaxUVuyrJyDgAnMfGXittNUMEUHhNPEPLbzxPHaXSgYViyaXGFqWJHuUavNBGySntICpolOhfbQiJDU"
e16375898101897025343 = "SSqdjvSbSulXZNIivwcvYCaTecskSzchPUUZHlfMmduwWHrqSnwvsDDLPDUBBPUDQENwVliFHmXSJuh"
K345 = 794
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg = "ScJKZCMtATTAnrsMzuyOFGOKFBiguRkExuUhLiCcASvuxNRDisIKwMIhlGIdIBWHmWhMtmymdtxqUUd"
lIIllIlIIlllllllllIIlllIIlIlIlIIlllIllIIIlllIIlllllIlIlIlIlllIllllIlllIIlIllIIlIlIllIlllIllIlIIllIlIllIIIIIlllIlIIIlllIllIlIIIlIlllIlllIlIlllIIlIIIIlIlIIIlIlIIllIIlIlIllllllllIIIlllIllIlIIIlIllIIlIlIlIlllIllIIlIllIIlIIIlIIIllIllIllIIllllIllIlllIllIlIlIIIllIllIIIlIIlIlIIlIIIIIlIIlIIllIIIlllIIlIllllIIllllIllIIlIlllllIllIlIllIlIIIIIIIlIlIIllIIIlIIIIl = 241
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = "rONFTxeQDEHHwBOPrNvtHcQJJpMgyOgIRoMPVkoQYkgSjZkXDjsdnMLyMXcmWGGXtOLEoZhPKhvvUrY"
zTZvyETxrNDKPQIyLhYaadUmEbUGZbyjXBETPdejBCOTOMDHkAmwUbbMNVRUnsUIBZHCbaZbpgKgvZV353 = 367
PeZEXwmYVgtQxneffzodMOxCoKNzSnonVYPHqVQvyyXIYTHiXIsGAiAEqhdOwudlhvCghCuTMAaLvbe355 = 688
T16375898101966023357 = 558
R16375898101966786359 = 371
IIlIllIIIlllIIlIIIlIIlllIIllIIllllllIlIlIIlIlllIlllllIlIIlllIIlIIIIIIIlllIlIlIIIIllIIlllIlIlIlllIlIlIIIlIlIIIlIIlIllIIlIllIlIIIllllIlIllIlllllIlllIIllIIlllllIIllllIllllllllIIIIlIIIIllIIlIIIlIIlIIlIIIIlllIIIlllllIllllIllIIllIlIIIIlllIlIllIIllIIIllIIllllIIIlIlIlllIlIIlllIllllIIIIllIlIIIlIIIlIlIIlIIIIlIlIlIlIlIIlllIIlllIIlIIIlIlIllIlIllIlIIIIlIlIIllIlIIIllIllIII = 160
h1637589810200158363 = "CrTTPCibWEOdewQBQqaDzYBueUmFynjrNsfBumtQykgCiVWGnZnGOvjqOgcXeWthbeRfWuLPyrVAxca"
X16375898102003741365 = 811
fMCxERKOeoPeYXdDPKOwumVpzgIxtNzLOaZqEsrDTlacWcVxgXpUStNWlNCigBSQztYYAYqWrunOZNh367 = "ZZwwNuAhmJOWQNybgVKhnBhIdNgqEzwXOTeVzoKnVaStsLJuoCIMVZXAYmbcjmIuOcmZRDZLhGegOYi"
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = "okXxaGGrStZySBMvJsxSLOKtvTIHvVSUsLOLxMbRCnNvWAJbGdDEFfTEzAPeRAAOTTrsSNnewfNewXP"
H16375898102014964371 = 445
IIlIIIIIlIIlllIlIIlIIIIllllIlllIIIIlIlllIIIlIIllllIIIIIIllIlllllIlIIIlIIIllllIIlllIlllIlIlIIIIIIlIIlIIlIlIllIIlIIlIIlIIIlllIIlIIllIIIlIIllIlllIIIlIIIlIlllllIIllIIlIlIlIIlIllIllIIlIllllIIlllIlIIIlIIllIlIIllIIlllllIIlllIIIlIIIlIIIIlllIIlIIIllIIlIlIllllIllIIIllIIIIlIIIIIIllIlIIIIlllIllIIlIlIIIIIllIlllIllllIlIlIIlIIlIllIlIIIIllIlIIIllIIlIIlIIllIlIIIlIlIIlIlIIIlIIIIIlIIlIlllI = 308
s16375898102039251375 = 732
AaAAaAAAaaaAAaaAaAaaaAAAaAaAaaaaAAaAaaAaaaAAaAaaaaaaaAaAAaaaaaAaaAAAAaAaAaAAaAaAaaaaaAAaaaaaAAaAaAaAaaaaAaaaAAAAaaaaaaaaAaAaaaaAaaAAaAaAAaAaaAaaAaaAaaAaAaAaAAAaaaAAaAAAAaaAAAAAaAAaaaAaaaaaaaaAaaaAaAaAaaAaAAaaAaAaAaAaAAAaaAaAaaaaAAaAaaaaAAAaaaAAaaAaaaaAAAAAAaaAaaaAaaAAaaaAAaaaAAaaAAaaaaaAAaaaaAAAAAaaAaaaAAAaaAAaAAaAaAaaaAAaaAaaAaAaAaAaAAAaaAAaaaaaAaAAAaaAAaAaAaAAaaAaAaAAaAaaa = "uopvFRSkTDzSxbkqSdoyAioAAvqSVfIwKkUykxVBKkThAXszQfhPnnnjNrMkWzayzpBzxeEtqNAgJdM"
lIIlIIlIIlIlIIlIIllIlIlIlIlIlllllIllllIIllIlIIlIlIIlIIIlIIlIIlIlIIlIIIIIllllIlIlllIlIllIIlIIllllIIIIIIIIlllIIlIIlIIIIllIlllllIIIIlIIlIllIlllIlllIllIIllIIlIlIllIIIllIIIIlIIlIIIllIIlIIlllllllIllIlllIllIlIIllllIlIlIIlIIIIlIIlIIIIIIlllIllIIIIIlIIlIlIlIllllIlIIlIIIIIlIlIlIlIIIllIlllIlIIIllIlIlIllIllIIllIlIIIIIlIllIIllIIllIIlIIlllIlIIIllIlIIllIlIIIlIllIllllIllllllllIIlllIIIlllIlllIl = "CIfXvXXCobVXpjmXGNmeQmCZbNLYAHaqEnuroumNQDIVpBtZqJBQGbgnEcETanXMQzScBrPlTsocYai"
IlIIIlIIIIlIIIIllllIIIlIllIIllllllllIIIlIIllIlllIlIIIIIlIIIllllIIllIlIlIIlIIIIllIllIlIIIIIlIIIIlIlIlIIIlIlIIIlllIlIlllIIIIlIlIllllllIllIIlIlIlllIllIlIlIlIllllIlIIlllIIllllllIlIlIlIIIIIlllllIlIllIIIIlIIIIlIlllIIlIllllIllIIlIIIlIlIIIIllllllllIIIlIIlllIllIlIIlllIIlIlIIlllIIlIIIllIlIlIIlllIIIIllllllIIIIIIlllIlIlllIlIIIlIlIlIIIIIIIIlIllIIlllIIIIllIIllIIllIlIIllllIIIlIIlIIIlIlllIllIIl = 567