O260 = 78
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = "pqyOOYHtJsZHBWRdNZRVKpUcyYxBbJDGxjKVMqpMKQDPncoBquAJkPiFongOYHmmJmVTrREyPCumDOK"
AAaAAaaAaAaAaAaaaaaaAAaaaAAaaAAaaaaaAaAaAaAaaaAaAaaAaAaaAAAaAAAaaAAaAaAaaAaAaAAaAaAaAaAaaAaAAAaAAAaAAaAAaAaaAaaAaAAAaaaAAAaaaAAAAAaaaaAAaaAaAAaaAaaaAaAaaAaaAaAAAaaaAaAaaAAAAaaaAAAaaaaAAAAAAaaAAaaaAaaaAAaaAAaaaaaaAAaaAAaAaAAAAaAAaAaAAaaAaAAAAAaAAAaAAAaAaaaa = "iQgTZmXxmlgUrRmZXCtSfYlgFlglmmcCbdvLaJqxdARSGzBwMDTaWVMFYGqgxtwxIAOyTPTraGYJOUw"
znnEQHHKtEyYoRiVGxDWtNgSNNGGLdKdMNkrvEojgpTqNagMQBAHiJEtuqQvPqedQfARKTlGRGHnkdl254 = "QdiFYbSZQiooSSAwjJOkyaIcCperwIboaGafFtVOTCcnWwkCVgWXlFJoiDrDzOwtKZjXsubFeklzQCn"
w16375891639941785252 = "BlaXLGnhVQvCeuPlhQjbYTzVDgdGBNtmANGYEhvnvjEIYkLcxXhLTMiocaifKdqRdfDiSlUKoDNgLtj"
JjxVQICphnPtRsSQOJBKAaLyqOqYNWdndCUmNhkcSjBrlmiIyVMtZCthgaLpUHyrZpAvkPRwHlKPCiQ250 = "PgIKLtiVRsanpVUkuawGwkqZNXTZATXaOrDAwjIxwRiiCfWOcJGxIoWeWggwsJGrvffjDVCCkBKJiNY"
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = "VQGFJiyPGxOKoqqTiBdqCrPvYdOzUSORBckysJUbvYfZCEnQGYZhxSPOvcfbwKWziSpaXHPsDMHDWNC"
oCfIwSeqTvqtTMIEAHczCeWnAEEVcCVVHiLcGUJzslLnHqiLxAtPiocGALTduuTWKPwqXgqoHDpaCSP246 = 562
IlIlllllIIIIlIlllIllllIIlIIlIlIIIllIlllllllIlIlIlIIIIIlllIlIIllIlllllIllllllIllIIIlIIIlIIIIIlIIIIllIIllIlIlIIllIlllllIIIIIIllIlIIllIlIlllIIIIllIllIIllIIllIlIIIIlIIllllIIIIIlIlIlllIllIlIllllIIlIlIlllIIIllIllllIlIIlIIIIlllIIlIllIlllllIlIlIIIIIlIl = 410
x1637589163992282242 = "UNKmrnFSsRRSGPuwjiEygDfUTqrbWFzPhramhZuFWJDEpAkLCTYrUmjOoyQrBmMkDtAScJMmEAzaMUj"
FGVHhtQVfOLOCVEnfLwmKGLDyeTiBERcVlVhvyhSlrGlWGhQVveBNYiBiCWEmEmwVChaLXtNIYxxxzr240 = "jlaTWFTHjwpJFvPoaPgtwOSYpcFWaAJxHeCoNnyTHuztrOyyzrulpOQmkiaVeFETSxSbMFVOchsZzFE"
zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz = "VGoGuhiHJyayUxsuYNckyHbJzlDVmjGlskzdidFAPMxceIIEaFYwBpPbdiNtZgKPrhMwmburAZGAbFI"
i236 = 522
y234 = "PVtysvBfyhynMZOBLoBTJiocGlevHElxSYzYWFRpcWVXLoevTyXGKecypiNxFLhPhCHePhfCoGwZSsh"
IIllIIlIlllIIIlIlllIIIIIIIIIIllIIlllllIIllllIIlIllIIlIlIIllIlIIlllllIIIIllIIIIIIlIllIllIIlIllllllIlIIlIllIlllIIIIlIllIlIIlIlIlllIIIIllllllIIllIlIlIlIIllllIlIIIlIlIlIIIIIllllllllIIIIlIIllllIlllllIIlllIIIIllIIIIIIlllIllIllIlllllIllIll = "rSzEFslNpKoAKnmqCeKBAyKeEsvNVvbPyEZgLFqVvfZUWPveUzFrebTpusDnBigDXSwsdfLJfNJTUQY"
jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj = "IUQSHIvpTWHKyZuGGmafbjVYsaDZUCDxOhHozORMDtVoxbLNMEzvawnMxkmXCEERSOLHVFJOUVLgnGk"
Z228 = "ZmoFKRDWBotgjKYwMdDJwbxftWGDQDBymWcoRYaajfvwzxUzBHQurZTVEdfJQaRTfsELFMVuJIoBNmp"
aaaAAAAAaaaaaAAaaAaaaaaAaAAaaAaAAAAaaaaAaaaAaAAAAAAaAaAaAAAaaAaAaaAAaAAAAAaaAaaAaAaaAAaAAAaAaaaaAaAAAAAaAaAAaaaaAAAAAAaaaAAAaaaAAaAAaaAAaAAaAaAaaAaaaaAaaAAaAaaAaaAAaAaAAaAAAAAaaAAAAaaAaaAAAAAAaAaAaAAaAaAaaAaaAaAaAAaAaaaAAAAAAa = "ibUhSARnfxvuceYmanLolNwdZNqbDfKhAecVcvPyvCSLcEuiHuxYYpsaltHEzmZtqdfGqLuztLuosFs"
t224 = 381
s222 = "jTSIhpebSlrqSINMSxaKhdJNkZfwClgCJcvzyAjHVeiBfNgHPVvIRVfQAxXaIevcCqgjJAEqFlVhTwK"
lllIlIIlllIIIIlIIIIIIllIlllIllllllIlIlIIIlIlllIIIllIIIIllIIIIIIllllIIlIlIIIIIllIIlllIllllIIIIIlIIlIIIIIlllIllllllllIIlIIlIIIlIIIIIIIIIIIIlIlIlIIlIIIllIIlIllIIIIIIllIlIlIIlIIIlIllIlIIlIIIIIllIIlIlIllIIllIIlllllIIIIlIIllll = "iUHamsRPCdOlJzoFdGqljznvGPUTxvqKgLwQtIixcPFBiGXDEgVoLzHMcCeXoEeGrTLIjUggIwOlTvG"
IIlIIIIllIIlIIIIIIlIlIIIIIIIIlIlllIIIlIIlIIlIlllIIIIllIIIllIllIlllIllIIllIIIlIIlIllIIIIIIlIIIIllIllIlIlllIIlIlllllIllIIIIIlllIllllllIllIlIIllIIIIIlllIIIlllIIIlIIIIIllIlIIllIIlIlIllIIIIIllIlIIllllllIlllllIllIIlllIlllIll = "iaZTTJwugTKBISZqacKgveZnbvIQbTCHjjPYnBfYvhvkVkWUfXZRJPhPFcEznDAxDlAyDfUKeBzqHTo"
aaaaaaAAaAaaaaAaAaAAAaAAAAaAaaaaAaAaAaaAAAaAAAAAaaAAaAaAAAaAAAaAaAAAAAAAAAaAaAAaAaAaaAAAAaAaaAaAAAAaaAaaaaaaAaaaaaAaaaAaAAAAAaaAaAAaAaAaaaaaaAaaaAAaaaaAaaAaaAaaAaAaAaAaaaAAaAAAAAAAAAAAAAAaaaaaaaAaaaAaaaaaAAaAaAAAAaAA = 288
MhzkgWrWfUPbFyrkVIxWKtKlbREcyTIRUmhgzeiOrSZwELqfHUfrQLtmMdLhwahkDEjzoNSRUhnaGKy214 = "ThTzaAYWPoDfrtrKVFNmaFtbgevXvCBzOrjrPBBlWqphaHtZRtoZkmtRwyqgSbLqGRCvZFwgWexdBvv"
U212 = "xCdypJcktQmehCkrDwzwbDlgpplksItECOHYeqbRgptojEJyLlxZqwkNpGdQORwftMIICseTMOuGhwZ"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = "BWwHVwPLzHKRxbEUkGOfwZPJYNeFoaBrUDNWMeeoiTIYdBnRhWoMWxGIXbbZXYJacDqERFqSlOAPjRf"
aaAaAAaaaaAaAaAAaaaaaaAAAAAAaAAAAAAaAaAAaaAAaaAaaaAAAaaaAAaaaaAAaaaAAAAAaAaaAaaaAAaaaaaaAaaaAaaAAAaAaaaaAAAaAAAaaAaAAAaaaAaaaaaaAAaAAaaaaaaaaAaaaAAAAAaAaAaaaaaAAAAAAaaAAAAAAAaaaAaaaaaaaaAaaaAaaAaaAAAaaaaAaAAa = 176
UBoXQkRQcTosAvqfDyVziZumZvlZtMyweFgtOJpIbTHPxvOfqbRPaGqgDSYWUyPUITDLJDJGLpswRQK206 = "uSDGRfCqCVVSgBnrMpFgNrQcFahYhIHMeQVHaIUeIYbscbatrmwiptePFpJzrGcTbEPRcUhWQWHLovy"
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = "wYcxitPQiXAdHRaDnaBmOVCnhbUqKgUGFynifbIsyvhmFATzdnliLREFVquIBpOMlVVwpylhxCYsFWT"
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = 351
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = 570
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = "GjfOwJLudJWVsRPFWwmliRjtwUqPVleFhBtBDEeFojiOuceAXJkYMMhgyDRPmHkIHboLRtDzoJWNNga"
rGCcEdIoqyMWJaXbChbpdsWYcWTdttTyHvtxoUAbyHlKYNWYkpIODwEviZRhiRBVRMHVLJxQFCxWcma196 = 485
z16375891639826636194 = "oWwiXxGBxeRffJKhTgCwWDBQnjadOnpUIgyiEDeMscRytceEWxbuhulrKUuXyDyuLuvZFRRIMnlLyPY"
i16375891639824603192 = "OhIeyktDBpxwTyUkuZGxbAttmLmGemwunYRdsfZakYUMeEGnlmdzvokMipNQPWyalTGPvELsyOrHTTt"
aaAAaaAaAaaAAAAaAaaaAaaaaAAaaaaaAaaAaaaAAAAAaAaAAaaAAAAaAaAaaAAaaAAaaAAAaAAaaAaAAaAAAAaAaAAAaaaaAaaAaaaAAaAaAaAaAaAAAAAaAaaAAaAAaAAaAAAaaaAaaAaaAAaaAAAAAAaAaaaaaAaAAaAaAaAAaAaAaAAAaaAAAaaaAA = "ELyjNqQNvoZhRlSiYCvDIILziaPWKapugUFIiJbgCeipNmAwnqWNLPuvCqlTxEzFfMVYGDpBmgTWUHt"
KoTSPdIfqiypgVjlicPDggCqHFuszkQGsxfNeArvqwYVyqKZVTuBJvGkFwhPhdMJslAzaOZOOeppLfI188 = "mwPXyllSlqczJANmwUzQFmgEWTSWGdswEHdUKvAbraKMDOUcXGUWKimiYqMvXJiHbBVMuxxiJjbqVCb"
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK = 148
G16375891639803636184 = 406
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF = "LszaCDjsXpRSCaYTDYkdVpluPXvcDrDmbEDPIVbKuuhDLlJHueCpJrWenqKqhGiVJooZiclYEqpSPqM"
W16375891639800563180 = "cdauwnTflVdjEhqGofcFCFFtUbYEtEyaZUqmLMersJIeBLdxmDgVNgSZLiADzjbbgdrECYRnWuAzhDM"
VuaCnWDgGabGrBIosUIYsGCkqhqQIgaDjpOhHNjwPjVIbIVNtDiKpzcACbCDAVCTDoxNUPSMhYIXhkl178 = "UbBHGZOGUIaDZvFPqePJOhQsTrdoiXbSVLkCiBjtgMpMUhEEMrHZYcwEwELzEtksgZuxIOsIPAlgbRe"
IlllIllllIlIIlllIlIlIlllIIlIIlIIlllllllIIllIIlIIIIllIIIIlIllIllIllIllIIIIIIIlIlIIlllIlIlIlIlIIIllIIIIlllIIlIlIIllIIIlIIIIlIllllllIIIIlllIIIllIlllIIlIIlIIllIIllIllIIllIIIIIlIlIl = 294
W16375891639788406174 = 366
aaaaAaAaAaAaAaAaAAaaAAaAAAAaaaAaaAaAaaAaaAaAaaAaaAaaAaaaaAaaAAaAaaaAAaAAaAAAaAAAAAAAaAAAAAAaaAAaAaaaAAaAAAAaaaaaAAAAaAAaAaAaaAAAaaaaAAaaaAAaaAaaAaaaaAAAaAAAaAaAAaAAaAaAaAAA = 338
AaaaaAaAAaAAaAaaaAaAaAAAaAAaAAaaAaaAaaAaaAaaAAAAAAaAAaaaaaAAAAAAaAaaaAAaAAaAaAAAAaAaaAaaAAaAaaAaaaaAaAaaaaaAAaaaAaAAaaaaaaAaaaAAaaaAAaAaAaAAAaAAaAaAaaAaaaaaaaAAAaAaAAAAAa = 293
D16375891639777057168 = 444
z166 = "EHApXKfQCYZnPKPsxnjVxdaICOVsfQXkSvlsUrNgBeMjsQxwplaUgtNEvKPnpyENznHDiNKDeNgovoi"
AAAAaAaaAAAAaaaaAAaaAaAaaAaaaaaaaAaAAAAaAAaAaaaAAAAaaAAAaAaAaAaaAaaaAAAaAAaaaAaaAAAaaAAaaaaAAAAaAaAaAaaAAaaAaaaaAAaAAaAaaAAAaAAAAaAAaAaaAaaaaaaaAAaaAaAaaaaAaaAAaAAa = "AeiQUKEEaIXPAAvwrlvqQBCnaxKFBcyqoLcXkyjewKLAphtwypMyLhcfQokscDlfDKHTqdzTMAGUlSu"
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "lZMwucoqMfBBJpSmRSokhYmGDazqyRyROgqZqVRUpLCRajlZiaWJUtjJwiYeDDiKUPvDGzRrvyjBfQm"
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = 280
j158 = 772
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii = 201
AAAaAaAaAaAAaAAaAaAAAAaAAaaAaaAAAaAaAaAAAAaAAaAAAaaAaAAaAAaAaaAaaaAAAaAaaaAAAaAAAaaaaAaAAAaaaAAAAAAAAaaaaAaAaaaAaAaaAaAAAaaAAaaAAAaAaAaaAaaAaaaAAaaaaAAAAa = "qjKVyhmGuPwtnKCWrvThavOOkkAyNvkkSvqALAnRCGLehpxFOlZXoiPcxHhDnfdOOyQTaTBqHVLeYfc"
lIIIIIIIlIIlIlIllIIlIllllllllIlIllllIlIlIllIIIIIllIlIIIllIllllllIIlIllIlIllllIIlllllIllIlIlIllllllIIlIlIIlllIllIIlIIIllIIIIlllIlllIIlllIlIIIIlllIIlIIIlI = 311
z16375891639759119150 = 267
u148 = "MzqyULKoSdJdFfYEQEOubtNfejZIZaDDDbBDjHEWSCVWxARZgadWlMpUukXFThauNnnkSxOhiCQGSxd"
PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = 561
aaAaaaaAAaAaaAaAAAAaAAAaAAAAAaAAaaAaAaAaaaaaaaaaAAaaaaAaAaAAaAaaAAAAAAAaAAAAaaaaAAAaaaAAAaaaAAAaAaAAaAaAAaAAAAaaaaAAaAaAaAAaAAaaAaAAaaaaaAAaAaAa = "TvJUazncQTlbzAftdyvLZNfrosUqFnHNRdwvtwxNhDvOHAaNuRIgXwPqEKjzEBgdkeMTQsciAHPXfUy"
dEtFtzFrzRcCjegkzSMNdmzCZrikpPtWEYrDGfxzeNovJrmWwCuIMfezQYyjbwrIummyJKcNpQtqVzG142 = 536
X16375891639751318140 = "VKndZzRRoNIkCrsAQeocXkjZCxGTOQVOSRqdsNHViNvCRRyiPgJLWuqtTXIbtftoFCJJFPrAXZjEgew"
W138 = 211
W16375891639749224136 = 676
z16375891639749045134 = 178
t16375891639748871132 = 379
z130 = "AILdIuegOIttMkLyMJWyGxezJlvgfEZEgVPYLjKjLeHELwLhHFnhixweXFXnyKfhSUSJMhpmxopYpio"
l128 = 106
a126 = 653
aaAAAaaAaAAAAAAAAAaaaAAaAaaAaaaaAAAaAAAAAaaAAaAAAAaAaAaaAaaAAAaaAaAAAaaAaaAaAaaaAAaAAAAaAAAaAaAaaaaaaAaaAAaaaaaAAaAaaaaAaaaA = 221
hjexeLtwCknQdeeYkVcLVGjgFjesktMhyMdClTcjvbfjfJYmFokTyAphiosrbkodVhtiRhEQpaamSwN122 = "EdhAjpXVRNQtStDDDBWATDeSBHCQvoykKXAEdRrufhFnDqnzcWwkihaeDmUlhGHSMByKUHbmsSGCIgZ"
sFNibAssnxGRUIGySReZwNFYIaJZGnaiGfqpkzRnsHidLJnrGlCAHiZlAEGQWNBfLvcvdkxOUqDxiFN120 = "qfhhizlljhvOXxZFqqnVrSchJQUgseQPUODnUyFMNSAgegcYzzvRUyHQVGXQKEdGkjkHFjocDrVdjMJ"
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE = 129
SBCkuKqomGvFBLjFboIArocsPfREeIoURGUMhuyLeFlAThBbgLZgbjTmNYOgBWfGiRSVbdHqwsKWtYP116 = "bdAIOnEZIvnZahDljyDazeChOIJUwjHRZSHnHSBaQEiriPuMXcoogTNVBgeAnAdbDoeTkZUJpYQpCpT"
O114 = "DkrmndProSyrMHyrCpnBkeRXfGEUqoNylxzkFITjbfDxQhXrgwohMjGuKgGQlmRFugmbEfNUTEtHYbK"
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT = 649
AAAAAaaaaAaaAaaAAaAAAaaaaaAaaAAAaAaaaaaAaaaaaAAaAAaaaaAAaAaaaaAaAAaAaAaAAAaaaAAAaaAaAaAAaaAaAAAaAAaaAaAaaaAAAA = 438
AaAaaAAaaaaaaAaAAAaaaAaaaaaaAAaaAAaaAAAaAaAAAAAAAaAAAAaAaAaaaaaAAaaAAaaaAaAaAaaAAAAaaaAaAaaAAAaAaaAaAaAAAaAa = 265
AaaAAAaaaAAAAAAaAAaAaaaaaaaAaaaaaAAaaaaAAaaAaaAAaaaaaaAaAAAaAaaaaaAAAaAAaAaAAaAaAAAAAaaAaaAAAaAaAaAaaAAAaa = "ewZDCkiDdNiprwWCBJSIoIsVCYJnEcjGSQruTVdpEvVCHlQuuDosWPmcIyiQIjvPlNorxwRpZOxVFqi"
IIllllIIIlIlIlIllIlIllIIlIIIlllIIlllIllIlllllIIlIlIllIIllIlllIllIIIlIIIlllllIIlIllIlllllIIIlIIlIlIIIIlll = "ZtTEtxuWxxzGnYculwCYiTcBrDhvBIFyeeBNeRnfXxZWckgUvDPhVZmkrqKpoEgGlMdjSkcSghFnrMm"
BuyxXLjFaSRZUpkLxochUslkMJxhfuQMrgKBFoyLxgTiFqEhvvUEysMSfQtOnfzeZYlWEblVAwaNhAN102 = 429
lIllIIIIIIIllllIlllIlIIlIIlIIIlllIlIIIlIllIllIIllIlllIIIlIllIIIIIlIIIllIIlIIIIllllIIIIllIlIllIIIIIII = 240
s98 = 146
IIIlIIIIIlllIlIIllIlIIIlIIllIlIIlIIlIllIIIlllllIIllIlllIlIlllIIIIlIIIIlllIlllIllIllIIllIIIIIIllI = 183
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx = "LzRfNaVIvNbUafLJXweIUEpQQgCyiijBFfVTollBXEqxHGLMYwbaXMHgOVFdVbjTwqxMdbARmsqlHBP"
gZTSFUyMhkDQZjAqkWiHaPwghTMqXErcsJLRwrqHdgqnRfyJhyJTdVZYfwAvJAXYcccCDEXXPlSWdqf92 = 739
I1637589163970622390 = "RyhKFPMwvBHgRzZTMvjobmIjcQPHVjwbDLuKGWfMHhivPGoEMcOljJIRgBCqkFLizbsvuhLsZdvRCPV"
AAAAAaAaaaAaaaaaAAAaaAaAaAAAAAAAAAaAaaAAaaaAAaAaaAAaAAAAaaAAaAaaaaaaaaAAAAAaAaaAaaaAaaAA = "ucujLfWulrrlnRQNqxLRFADYygebAqYEeLPOrNzOrDPJcDKFKLlIemHcSYSEkmHygmnnwvBrFVdForr"
lIllIllllIlIllllIIIlIlIIIlllIlIIIlIllllIlllIlllIIIIIlllIlllllIlIlllIlIllllIlIIIlIIllII = 249
AAaAAaAaAaAaaaaaaAaAaAaaAAaAaAAaAaAAAaaaAaAaaaaaaAaaAaaAaAaaaAAaAaaAAAaAaAaaaAAaaAAa = "LBSkufCORJDHanSCUnlYUUefwOyiNLjXEQyPDEzPanbdSfEjeuwFuyinOGcqAYFeTYpjFFNZPoiavXV"
aAAaaaaAAAAaAaaaAaaaaAaAaaaaAAAaaAAaAAAAaAaaAAaaaAaaaaaaaAAaaaAaAAAaaaaAaaaaaaaaaa = "nqPomzjkPEbOKEBQDZAKGNTZPXQTYaFiLDewFUBiBlhTmeHZVWVqcWmCQlPqBVCOSLItZlqlruJzYQU"
v1637589163967224480 = "AUrAIVdPLxKDjNlBNjCVomtMbOnDDEPNEIhNAGbcPKaLHFbgJsjlpciofaVRtBUvKppHsqIOKHNxZYp"
TzsulhjzgqsTByjZVqOdjXgrayaTBpaUkCGcglTykGaKfEUHxNkDYpzpZactJxiQrWpCUFElaPKUtOb78 = 296
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 195
HTmAfyyGjYuWHSTPYOQtoXxXThMTniqwmwmRNONXaiRWnSFvYNNTNCNPjQZHAvjXgqrwLBxSAjvLXoP74 = 507
X72 = "QInyJnJYrjOBskIAGIYOuuFIEGBsULsYwazxugIWjuWCMfRxqQHVPyLyZqoocLxmNdugGsFjcWFLGTS"
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = 303
C1637589163965752168 = 293
IIlllIlIIllIlIIllIIIlIIlIIlIIllIIIIllllllIIIIlllIlIlllllIIIlllIIlI = "wDKWIVoIfYVaPBsUfhBHxZkxkkLpDhIpedeaFIWEXqVGrzwlWbkpxZGSDTmWNKMaxFMFWQQgMMidCnq"
llIIlIlIIlllIllIIllIlIIlIlIlIlIIlIlllIIllllIIIlIlIIllIIlIIlllIII = "CrZHjYUOVoovLMLgdNomKSnLBYLONQQjtEGGWAstBIiJkSKsdExNWbrPeODkjvtrDogSMDxCWRQNVCi"
WUBtMGITUrDDPwNGVyNuObGqpEsYbLjomKPJFpgBzbhDBizInfJWrkoSjaPkSoNrePlNEzOZLZFEtEo62 = 295
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = 218
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = "YZrdrVzvmUsSRHbwQuiNtLbcynuTTeIHCmalVnbASxrYoBZunhhMsuQDmAMKpbDOkEPfuuLEdddQOPO"
e1637589163963322656 = 316
AaAaAaaAaaaAAAAAAAAaaAaaAaaaAAaAAAAaaAaaAAAAaaaaaAaaaa = 441
llIllIIIIIIlIlIIIIlIIIIIlIIlIllIIlllIlIlIIIlllIIIlII = 565
g1637589163962858450 = 198
a1637589163962632248 = 359
h1637589163962575746 = 314
l1637589163962287244 = 363
L1637589163962028742 = "DNnyutCKjGmVLeCQYbmBILCBioAqKBDkeDsOMYlrKnuYNIeENKGlQVykQDywRAKHXuyUSMmndkDquXW"
z40 = "qMXfrrildNjuhxLppDtLLSznaxHSthQLenzcyjgEVFspnzgaPRhNNmsbPeYohDASLmOwQonZZQsKWYT"
Q38 = 265
mWkXUDUfONUfHquTunQZBoaKiJvYTOHsHHaAxkCJywZJwLrEOGgZqTcfMPJrSUFrTbrfCZknPiuSNEy36 = "gnheNwpspaITWNtVLGMSWFOOEhHuYhqHxDXUFlpNnySIwDFLyGnqeMvPIApgWJKhuSimadqrvviHZtK"
wGfjJiqkhGqxwPFvklxWDDTHkQaZwxDKgrFKKAikFsxgrhJlUfZcRpmQAXzmJBwtNCVsZmZLCeYuQmN34 = 603
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 471
aAAAaAAaaaaAaAaAAAAaaAaaAaAaaa = "mukTkXoUCHJSjYueXQVZfbEaYRvwvoQirCoLMaLHdsafcMHJGFItusZYijjiTQtQrbiqLwREjBgrSJK"
I28 = "iuuJfIncTUlwBIiWcKPjZGKqVEfgDxvQwJHQZjqEyvWGMElbvoALgCGxMzYmXiXjUXKLTuMcnNmxaXs"
H26 = 457
I24 = "fZQDaduqpOkXWVnKoukIpFQOkfEEpseFVaAKCVKnvZtrFjqJfwyfqePIECSDURxxeFbMYlkBJLfWcym"
P22 = "GbbzAkSABrXmyopROUCjSZKRQVWoNPZukvHwzCRCnydMVPpatPZLyGAIQfGMDWyGmDHYhdpZYYwftpz"
X20 = "yANnTHDFiHnkpJVmAezvaXyygrEUbenNoVuAuvILrvJUtcshIGdoTUjKszNEBfdQVvbTaSemAHkPscv"
glwoopJfwmVeVbOcXrIbzrVmfQAnhoEBEIaeYNIkFdrsMaZalddMIhvJpbVHoPEkWFRTPSnSeUQwXId18 = "oOisaaTbhhysfEZVekNBjdUQLsOJLzxqNNxJzzNcWyXHSvixypsMAjQumXJmGDNdyedTHlwLJXpvOmJ"
lIIIIIIlIllIlIII = 308
zzeNJRDugaoTmBTPPJNNamkqAMwzybQUfSGEoMwvMhfDFzqWJIFGfmejyyUqwlJQkIGbZOiAtTEOgLi14 = "rgBuyOGDuMarUcSGjOTFCzufkaLGdiNWPhIoBqhtJcLpvKJIfcHqypgUxbLtwGLvZSoeJCqgBVFjFCv"
GXFdkubNulcNFyGJGpqEmEBwgjiggQYmBxwKtBOzwmdNIGPstbzPCzbXMCDMnWBjTcxRazUkUpGsRlv12 = "cRMnFirCqRwIOCvGaszrdALypSLZtNaIDdLCDtoqwQOgoJPaHuaNLLhbuFDUUwKuFkEPyVLWplmVaYO"
AaAaAaaAaa = "LznaYBKCCPjbdIoUhcaromOEGqTyhTuJtuBkCbhJrKZrumorDsjUZjCSvjWjoaEIEbWJMhWsnegfjpY"
L163758916395847188 = "obrorSdGaPRcEvhDrEgXbbSxmwfmMlcwCwULgWczYeaIIELFiYJgTIQIboPSfyATeFHShISjghyzUFZ"
ZdZFUVlWDxrweVrWikpwNsUXpeSGSUFghjrHQUjCuIiCHiRzhlddKaIPIcJUWWpWGTOoQGpsksvJkKR6 = "RpwanGqjVhCGtOuqyiGocXCciWUGOTtopfeaDPAqpTLKIUsXQcOWhZYNycMrEVVjMJZcbwWhbPdiBNi"
aAaA = 260
lI = 158

#!/usr/bin/env python3

import os
import sys
import time

def lowprint(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(2.0/90)

z = ('''\033[1;33;40m
 ___________________________
|                             |
|                             | 
|           1 RUN             |
|           2 SETUP           |
|           4 CR              |
|           5 UPDATE          |
|          99 EXIT            |
|                             |
|_____________________________|

''')

aA = ('''\033[1;33;40m
 ___________________________
|                             |
|                             | 
|       1 SETUP TERMUX        |
|       2 SETUP SHELL         |
|       3 SETUP UBUNTU        |
|       4 SETUP KALI LINUX    |
|      99 EXIT                |
|                             |
|_____________________________|

''')

YYY=('''\033[0;32m
╦═╗ ╦╦ ╦╔═╗╔═╗╦╔═╦ ╦╔═╗╦ ╦
╠╦╝ ║╠═╣╠═╣║  ╠╩╗╚╦╝║ ║║ ║
╩╚═╚╝╩ ╩╩ ╩╚═╝╩ ╩ ╩ ╚═╝╚═╝ o
=================================
Project จัดทำโดย Sakol Thaneerat ได้ดัดเเปลง ทำเพื่อเป็น Tool ในการใช่ DIRB ได้ง่ายขึ้น 
''')

aaAA=("______________________________________________________")

os.system("clear")
lowprint(z)
lllll = input("number : ")
if lllll == "1":
    os.system("clear")
    h7 = input("link : ")
    lIllIIIl = input("name-word-list (1.txt): ")
    os.system("dirb %s -lIllIllIIIlIIIIlI %s" %(h7, lIllIIIl))    
if lllll == "2":
    os.system("clear")
    lowprint(aA)
    P1637589163954722210 = input("setup : ")
    if P1637589163954722210 == "1":
        print("termux")
        os.system("clear")
        os.system("pkg install dirb")
        os.system("apt install dirb")
        os.system("clear")
        time.sleep(2.0)
        os.system("python3 run.py")
    if P1637589163954722210 == "2":
        print("shell")
        os.system("sudo apt install dirb")
        os.system("clear")
        time.sleep(2.0)
        os.system("python3 run.py")
    if P1637589163954722210 == "3":
        print("ubuntu")
        os.system("sudo apt install dirb")
        os.system("clear")
        time.sleep(2.0)
        os.system("python3 run.py")
    if P1637589163954722210 == "4":
        print("kali")
        print("kali not setup")
        os.system("clear")
        time.sleep(2.0)
        os.system("python3 run.py")
    if P1637589163954722210 == "99":
        print("exit")
        os.system("clear")
        time.sleep(2.0)
        os.system("exit")
if lllll == "4":
    os.system("clear")
    lowprint(YYY)
    lowprint(aaAA)
    time.sleep(1.0)
    lIllIllIIIlIIIIlI = input("Enter...: ")
    os.system("python3 run.py")
if lllll == "5":
    os.system("clear")
    os.system("git pull https://github.com/sakol289/dirb/")
    os.system("python3 run.py")
if lllll == "99":
    os.system("exit")
# else:
#     os.system("python3 run.py")
H16375891639580331 = "RoXMRDDlEEEUHjdSXKPGzmVGUiFsfeBPyskdFUMmSjhIHxkpuwqxBGRdeHRoOwILponqzVwCnidTqkq"
III = 486
lllII = "NrbfHDiFgWbjqjmwqyvcATVtsPUIjZYGGfTmSKSxrgzcfMFvfLdJFlQXRZginseGiAwkMGnNcbBuNIi"
IIIIllI = "fCbcBYTmrjdyLruudGNLuxwfTYkDVJfaegILdDeAJprLYslZRAtmRlaerMvltDIhuvDjPjRegEJALwd"
IlIIIIllI = 374
AAaAAAAaaaA = "RbcYtWkKIjIIVNvuKpHxzQfSpdBHoLJjljdXCWnhXKRUACpAWTfsKmCDmeUBQwsXcjsGZrcRohaXhzv"
lIlIlIIllllII = "HNRPonERkyJSthBiMgrGRAQNLAikCleqnCjTQPtGQLateIItDSUYETFttOVrKOqoytzLngRkXewdgLF"
D15 = "LAgKXAxiFtzjdOzHgffwFqgXEExVSnHRbRBjAHnZWMpDTXvCoPPoYRRSnoMoXtyxQnAZjtSjwaCAidk"
v1637589163960071617 = "DlpZuGrDbjamUMVgekyRPgRxRpmOhbWslMxbCgpQQqBPYwLoLsETyOEmxIqRqIAKiNIpNzGGhcBhAEg"
AaAaAAAaaAAaAAaAAAa = "JKBbkmPwjuySHCyPOWXIoCQPerNpirHXZdKDirSDGtRLjVJcqAdgYUQxqzptHYNbOvLZrycdhKLPnxm"
AAaaAAAaAaaaaaAaaaAaa = 173
fffffffffffffffffffffff = 331
F25 = 243
yhXgmLAtLZOAfEZPPPSKwJlxLYpkLliUGdMTkKhQwCutotqXLLuqIrSQxnWyTFOlFcqhLVvDcwprZUv27 = 365
AAaAaAAAAAaAaAAaAaAAaaAAAAAAA = 413
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN = "FtuqIOfbQGkaEdsUJugRDhzFyLYwrLonnrqiBHcobbdpGQDTfWunRVopegMqihthyHKwvYVLMPLwMQV"
YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = "BOgAwiFkJbFeWHsEJZQhBuxhahwdKzIyCfoDXcguLAoLBgRrcmKXVjSrsrqxUnLBMqdMWjltfesuUoL"
n1637589163961727435 = 196
fffffffffffffffffffffffffffffffffffff = "LTUyrMzfAcswgxYSfYyLRKYrJZqGQRckXKLYnGKDvBfZbPBUhSpMqiNRHBcVnLjkpbgrdWwIiDjyRdh"
D39 = 503
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = 330
M43 = "XkNCPUoUHqgHjPicLAclczYWbfOYzJxGglpFHvjUGvqbMPSYtElvZEyUcYUzfCdJXjEoyaNZciuHfzp"
wkndqMKKBFGnOWDQsNZPuOiasQFiWZgmzHOIzAYpFRikTsgMFQOrTpxcbracaOaedHQNJXmhYibmXsm45 = "vBXwzjIraFdTLgrAwtazfsAlqNNYuJTDvswJuPboApnqdsaebETXjzFWAlEfDRyNPTWVFnLNYYdbhJJ"
lllllllllllllllllllllllllllllllllllllllllllllll = 122
aaaaaAAaAaaAAAaaaaAaaAaaAaaaaaAaAaaaAAAAaAAAAaAAa = "IHeApAeiGVIgsEePuIPRCWXoAybVXXAyGXnDmRBNVSTaJTkpKMUnKwdbBkHSKXhlqivrrKGBpejIrvK"
f1637589163962885651 = 588
aaaaAAaaAaAAaAaaaaAaaAAAaAaaaaAAAaaAaaAaaAaaaAaAaAaAa = 434
HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH = "qxGhSaKJWRqIQZLqFKzFbssIEoRdoDSNIafNlDqAmFhhYlhlggTwtQDLdxDijglNMizwPzCvcoYBEbe"
aAAaaAAAAAAAaaAAAAAAAaaAAAAaAaaAAAaAaaAaaAAAaaAaAAAaAAAaA = 285
SlwNijiyzmlfcqVIUDdaIKVeMhcVXmpbJJPmONZGggRqXnbTnFddTuRIkyByMmhHvkmZwnAnagpajAM59 = "CKtAFZvlFINYPDykXkMjdsBwUivYzNRISsomTvkosWjNmmhwBfgMxDcKXMwpXtfxIXIRDpgMyKjZDTA"
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh = "DYlxQsCGbAflvuIvTlCOmypylDgLSiWTtCZpXHrbPpzqVXMtEdxUBjIXnfNcecCHeyCkGmlxRPMcrxH"
A1637589163964383863 = "yszCuutlpWZKfEtPrfMHaeWEudckRGGOorwnqTSstrxzSoLNJfvpFesbihjJquXbNsVywyIOeqOyxUn"
lIIIIlllllIllIlIIlllIIIIlIIIIlIIlIllIIIIIIIlllllIIIlllIIlIlIllIll = "mKqcMqrWtJwXzcFyrIBHZWIwNoaSSRnHHVfkvxjLoXktmqGnwyjeEvrUnPJZaAJmtGHhrbzhPzTOPwu"
IlIIlIlllIlIIIIIlllIlIIIIlIlIlIIIIllIllllllIIIIIIIIIlllIIllllllIIII = "loxVYFeeTWxZtTwgPulnYHzEyvttHGIovIUgrENFFPZHTLWUOiPSiGYmuyuQIWAcAzotoeDZGXbKdpB"
IIIllllIlIlIllIIIIlllllllIlIlIIIIllIIlIIllllIlllIIlIllIlIlIIllllIIIIl = 339
IlIlllIlIllIllllIIllIlIIIlIlllllIlllIIIlIllIIlllIlIlllIlIllIIIlIllIIIII = 885
DgZNifmjFIYOBDQfZiWRHvcvVwWdmKPhWVqGKHafNIOXBBcOYTRxbBipAZuqBcWaTEmjWBndrWGccan73 = 72
IIIlIIIIIllIIllllIlIIlIllIIlllIlllIIIIIlllIlllIIllllllIlIlIllIlIlIIlIlIllII = 379
V77 = 529
AaAAaAaaAaAAAaAAaAaAaAaaAAAaAaAaaAAAAaaAAaAaaaAaAaaAAaAaAaaaAAaaAaaaaAaaAAaaAAA = "cbCnfIcrSKmBjAhmedljzVpdFCwmjnFrUQuBwccYniCEHXxgNTYydTbZabkAPkKVpbJoQwTFGuLgftW"
EcvBKFXGdQIqxWAirfydcCSQELrxkpoKbMuOXgLHkEIhZYdslfAiTkzxwZgMeaPrfmivOveordgQCVe81 = 224
QRnkxGtsPnOlLFNIuJBcZIqaZfbbHwDNWnBpUKjRDOIPgbqbicNEJwkGoxVGUexmudifKwaEuiGAUyO83 = "gNkRTwBBQxJLDdZEUyWneCoIwWQcRtzcfGQVaZTDMQxIiEthSrpbMVcrblPuTKIKZHIEhAmhvhQzAUO"
V85 = "HtMpXGMNPvksREzFoOLPwNBELprccJOBXTfrLXtviwyujriGnyJadRZiakGHgrlQIfwElnoMtokDNJK"
lHBmEycqhFEZSMantUWoRQcWJoHQGvxiHPRNVcsCBrBXGugwZkQRGSOsNFjzDLOmMuvUGhirNVpKwsx87 = "pQSlLQRjNlzMLahDxseMFaxbkWjexqjNapKYesYExtkZDJnJcFMpAXWDCAxKFmxYuXJlIJgIlwepndg"
IlIlllllIIIIIlllIlIlllIllIllIlIlIIlIllIlIllllIIIlllIlIIIlIIlllIllIlIlIllIllllIIllIlllllIl = "fMsfARpxucjJrnCktkZALUYUQWSEgwJRhiXtloUYtkohfzlxfftzhWEjSpBngVYViaVQlkEfrlzRsHT"
IlIllllIlIIlIIIlIlIlIlllllIIIIllllIlIllIllllIllIlllllIlIlIIIllIlIlllllIIlIIlllIlIIIIIllIlIl = 176
AaaAAaAaaAaaaaaAAAAAaAAAAaAaaaaAaaAAAAAaaAAAaaAaaaaaaaaaAaAAaAAaaAaaAaaAaaAaaaAAaAAAaAaAaAAaA = "HuezrmAxrLlbDaVougzKZfZVbzRWZjtRksReYEmtuworOfvOCXasxnHeuqWRmycPrsQCYygifqFYGiL"
X95 = "OfrgFffPnQOqoyxLyheWcKjsLVcrBdbeVTCxnjvbMOZQYBLzUWGtyVoeMKSSmEztdzCStmvSlMcJisI"
IlllllIlIIlIlllllllIIIlIIllIIllIIlIllIIllIlIIlIIllllIllllIIIIIIIIIlllllllIIIlllIllIIllllIIllIIIlI = "UzcJBhbXzcvfCCurHZMHiqhlTjXtZqOypGEVwyrRFGxQKZjTVAbSWOygYYwFtshbmIwNjBBYRcBmxcp"
pShrOaErtamuVpGoUdEOCPSMvSZEtmZCJoScIlgFFqZoRWEacZRnmpZeuQiPlaFTxzDqdOPncoLEFyZ99 = 254
P101 = "vKFpFNHrUvxXJAcHZKqGesukkJzslXbpIHFbagUIUdjBwIpcQocesHglBxOKpYGFGwdIEalXBeeelTn"
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = "XdtcQtmFvfiUonVVyluRpuilnEprarZYNMaGgQsqbYUyNycscVvwtMmDJpKpKjSfhAUzCFQHjkPZvge"
aAAaAaAaaAaAAaAAaaaaAAaAaAaAAaaAaAaaAaAaAaaaaaAaAaaaaaaaAAAAaaAaaAAAAaaaaAaAAAAAAAaAaAaAaAAAaAaAAaAaaaAAa = "ShNbVQvQxdHGElwWMUrAXsdMfxKkOxceVVuSreJRHNMcWmrUjxAQdkXuZvIHQizyUURUvvOByFWznpm"
AAaaaaaAAaaAaaAAAaaaAAAaAAaaaAAAaAaaAAAaaaAAaAaaaaAaAaAaaaAaaaAaAAAaaAaAAAaAAAAAaaAaaaAAaaaaAAAaAaAAAaAAAaa = "CjxWsBflugZqXuJMuALkpzdiaQKJNhVkATahvbuBRxMRpLxqBVKFPhIRbbKZxphtRpqqrjSGUBmXAGY"
MGOhMQvVsZWRLQuaMrwYXeBqRBRBOnWLJHxzVYEULOEiopUmMujYagMoitsiYuOSMmHjjHZKegLXBCj109 = "eAFWYncplfQyuSGOyBcapuidTNboRIZaJfdfuNjFyKYjEXdWijFfQzIyawTVwblARpsqGxaVpoCvdNN"
aaaAaAaAAaAAAAAAAaaAaAAaAaAAAAaaaaaAAAAAAaAAAAAAaAAaAAaAAaaaaAAAAAAaAAAaaaAaAaAaAAAaAAaaaAAAAAAAaAaaAAAaAaaAaaa = 348
D16375891639735458113 = 399
IlIIIIlIIIllIlIIlIIIIIlIlllIIIIIllIIIIlIIllllIIlIIlllIIIIllllIIlIIIllIIlllllIIIIlIllIIIlllIlIlllllIIlIlIlIlIlIIIllI = 263
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm = 392
N1637589163973876119 = "VhThxMcwJEIGBqQIfDjxcSEFHfvjRlZwZwweRqQFcJopODcKtjQSeFWlzCfdhIsfgEwKdKuWSjOEsja"
aaAaAAaAaaaAAaaAaAAAaaaAAAaAAaaAaAAaAAAAaaAAaAAAAAAaaAaAaaaAAaaaAaaAAaAAAAAaaaaAAAaaaaAaaaAAAAaAAAaaaAAAaAAaaaAaaAAaaaAaa = "wkvMbUSSAvQZjjujfGUfCPkQlkgZXCRBxhhCIBKkzXZPjHKghrPrWhDrcdhGpqAewmUHrxlyGvpTBrF"
llIllIIIlIIlIllIlIIlIIlIlIIIllIIlIIllllllIIlIIIIlllIlIlllIllIIlIllIIllIIIIllllllllIllIIlIllllIlllIlIlIIIlIIIIIllllIllIIlIlI = "mtCVpaCAsfIHireJfRGtoUfMgJoGaEZtSVTMyofmrRKuCwJRoBMwqjmFXQKLtKFzrOOhGYsHAwXPacp"
IIIlIlIIllllIlIIlIIlIIllIlIlIIIIllIlIlIlIlllIllllIlllllllIlIlIIlllIlIlIlIIlIIllllIlIIIIllIIIIlIlIlllIlIllIIlllIIIIIlIllllIIll = "wZPUbedsxEdJztqwnqOjTZLDqoKspanQmivLWAYmGltdrRGhSPMwytQMiRanIzQuLwAcEOcBXusdBRi"
aAaAaAAAAAaAaaaaAaaAaAaaAaAAaaAAaaAaAAaAaaAAaAAaaAAAaAAAaaaaaAaaaaaAaaaaaAAAaAaAaaAAaAaAaAaaAaAaaAAAaAaAAaAAAaaAaaaAaaAaaAaAaAA = "zrpyRLWKtXviYiSTqlwBkLhyWKBmHnAcZmYVBYCCEuOahSSOvFyPdePcqeQWGtMUjMoFcIhNFTXvXGi"
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww = 560
N16375891639748728131 = 365
W133 = 749
E135 = 121
U16375891639749813137 = "eVSBdZyQbRnibnIKdKPtMMnLtVUvXJlmxSPggOiKQzhQFIajPYpGoCsxWcNzcTEnawypIJwDQsVjLdY"
aaaAAAaaAaAaaAAaaAaAaAaAAaaAaaaaaaAAAaaAAAAAAAAAaaaaAAAaAAAAAAAAAaaaaaAAAaaAAAaAAAaAAAAAAaAAAaaaAAAAAAaaAaaAaaAaAaAaAaaaaAAaAaaAAaaaAAAAAAa = 340
aaAaAaAAAAAAaaaAAaaaaaAAAaaAaaaaAaaAAAAAaAaaAAAAaAAaAAaAaaAaAaaaaaAAaaAaaaaaaAaaAAAaAAAAAaAAAaaaaAAaaAaaaAAAAAaAaAaaaAaaAaAAAAAAaAaaaAAaaAAAA = "ZXaVRKsIuSrHsGMPfAsLCKwPxWpHwlyXDaztwfkyPHYWbhXnMkUcUBWrdKNmzUiodwZINKOfLJCrRkX"
RnOYcNqZUxCzHTvOTXhTvgDLcduvHEAnNewvPkGAxRjgSCsgKsGQUNvWnkZiShDfAmcRQVwASBubNGy143 = 264
IlllIlIllIIllIIIlIIllIlllIIlIIlIlIllllllllIllIlllIlIIIIIlIllIllIIIlIIlIIIIlIIIlIIIIllIIIIlIIlllllIlllllIIIlllIlIllIIllIIIIIIlIIIlIlllllIIllIIlIll = "RiQCSSxvyEfTQMipfMlxtctYihAlBcUMmNaDrPTZjMxvyxlXuZEHrtwrorAuqLlQGUGiEHjWcorYUZS"
l16375891639757695147 = 375
g149 = "DOnTOrqhdErRUwKxDdChbNBipOTjuMhtUXtsYUrNVbtEeASJjjdPgjcUCDQXVWgKFXgRdHRSwkNStHb"
Y16375891639759254151 = 253
lllIllIlIllIIlIlllIllIIlIIlIllllIllIlIIlIIIllIllIlIlIllIlIllIIIlIIlIIlIllllIlIIIlIlllIIllIllIIlIIlIllIlllIIIlIIIlIIIIllIllllIIIlIlllIIIIIIlllllIlIIIIllIl = "gsOMRbGPFFVKCTbEfnAMERaVUVrVEzGIQPyHRcmnLyRSBThUhDfDBsOykJDhsqduwjRYOZXdKYHTpOA"
z16375891639763181155 = 453
lIllllllIlIlIIIIIlIIIIlllllllIlIllIIIlIlllIIIlIllIIlllIIIIIIIlllIIlIllllIlIIIlIlIIllIIIlIlIIIlIllllllIlllllllIIIIllIIlllIIIIIIlllllIlIIlIlIllIlllIlIIIlIllIlI = "nioJKBPSBDXLrCKalUKYNFXnhTspzWfVUasYiNnsiuYTYpxLPCVJmaOhIrfypsjEtDZKbywwCIQVJEa"
N159 = "tMUsGucEbUrrqZbGJqPlRWtQsgsUXFlXileOXrwBRSAjBBhMCakPsisgiaecGBsjYmPAkKDnemxlSgc"
A161 = 278
aAAAAaaaaaAAaAAAaaAaAAAAAaAAaAAaaaaAaAaaaaaAAAaaaaaaaaaaAaaAaAaAaaaAAaaAAaaAaAAAAAAaaAAAAaaaaaaaAaAaAaaaaaAAaAAAAaaAAAaaAAaaAaAaAAAAaaAaAaaaaaAAAaAAaaaAaaAaaaAAaAa = 300
S165 = "qFhQkpOUetWghggOCYWzNzSjWJxRuHQadCEnlJsNdnwwwGCllvZvOEDDPRjhSSUEVHbYaDRxqkRLjHd"
aaAaaaAaAAaAaaaAaAAaAAaaaAAAaAaAAaAaAaaaAAaaAaAaaAaaaAaaAaAAAAAaaaaAAAaaAAAAaAAAAAAaaAaAaAaaAAAaaaAAAaAAAaAAAAAaAAAaAAaAAAaaaaaAaaaAaAAAaAaaaAaaAAaAaaAaaaAaAAaaaaaAaaa = "riFDztTFJVaVpCfTKlfnZlWHkNvaDLlyasYIyZHMAxLUmbwrBNfySCETwfswMwmvTSzLTNEyJqXsDNK"
aAAaAaaaaAAAaAAAAaAaaaAAaaAaAaAaAAAAAaAAaaAaaAaaAaAAAaAaaAaAaaaaAAaAaaAaAaaaaaaaaAaaaAaaAAaaaAAaAaaaAaAAAAaaAAAaaaaAAAAaaAaaaaaaAaaaaAAaaAaAaaAaaaAaaaaAaaAAAAAAaaAaaaaAA = "WjOYFuiPzCuPHiiieljcGqHWoQKFRVJYVLpxqGcboLdhVBjJgLegNUgETiBhmbQqUApBWbeZhiESTGo"
H171 = 380
S173 = "NKtuDWkpPFgmYOaKjWyzslnlhSIiLeRsvEZclkQnDDKIEiZoapPepSPnHdGVuWlBNYUrpNaJqserKzs"
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = "OiHKYCIDhrynVBodGiTfVdYJUUroTUcrPtboQRBOJKzFjsUvLVXTaKbnSxTTBdDPuqxtWhweCaiXSna"
AaAAaAAAaaAAAaAAAaAAaAaaaAAAaAAAAAAAaaAAAaAAaAAAaAaAaAAaAaaaaaAaaaaaaaaaaaaaaAAaaaaaaAaaAAaAAAAaaaAAAaAaAAaaaAaAaaAAaaaAaAAaAaAaaAaaAaaAAaAaAAAaAaAaaaaAAaAaAAaAAaAAaaaaAaaAaaaAa = "cmnslxJIOGKOZlHNOCknckdZaPDcSKjAfLRgkkPcDNwiIRKYjkcbhPheOawcWgLbrrMXRcCabdBtDzV"
W179 = "EsdLZzABoDYGRjjfdDvgVSepoEJEfVasYyfUurxOuzuPRMlwIPcOgoiOrQLABhgdKxRwhiFlKepPCHn"
AaAAAAAaAAaaaaaaaAAAaaAaAAAaAaaaAaAaaAAaaaAAAAaAaaaaaaAAaAAaaAAaaAaAAaaaaAAAAaaAaaAAAAaAAAAaaAAAAAaAAaAAAAAAAaAAaAaaAaAAaAaaaAAaaAAaaAAaAaaaaAAAaaAAaaAAAaaaAaaaaAAAAaAaaaaaAaAaAaAAA = "rlHvuufxEbHPDFJiDkNIyALVSnrROffttSJYiIvsFgZFrNKhlBEPjiZdYRwEuznySIFllidKHVOIUVd"
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff = "BGzNbxtlBVadJlxpbiTNjVLWlEACgIvaXaAXYuDBZIkHzEzwFTYaiRvgtgsXuXWGXcAFvJvQgZdMtKy"
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW = 614
aaAaAaaaaAaAaaAaAAaaAAAAAAAAaaAaAaaAaaAaAaaAaAAaaaAAAAAAaaAAAAaaAAAAAaAAaAAaAAaAAaAAaaAAAaaAaaaaaaaaaaaAAaAAaAaaAAAaaaaAaaaAaaaaAAAaaaAaAAaaaaAAaAAaaaaaAAAaaAAaAAaAaAAaaAAAaAaaAaAaAAaaaaa = "zLrKLEEIELzDZZUKslstWuuebWLqRVQzRsNSdYRfTwUdhicqkGFxFaHFejkUNzHwYXffRbAPYsXCRMO"
aaAAaAAaAaAaAaaaaaAaaaaaAAaaAAAaAaaaAAaAAAaaAaAAaAAAaAAAAaaaAaAaAaAaaaaAAAaAaAAAAaAaaaAAaaaaAaAAaaaaAAaaAaAAAaaaaaaAAAAaaAaaaAaAAaAaaaaaaAaaAAaaAAAaaaAAaaaaAaAaAAaaaAAaAAAaAaaaAaaaaAaAaAAaA = 436
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR = 303
Y1637589163982511193 = 465
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = 464
J16375891639828932197 = 282
iKTATeHiqZDXzXBvPDmcVJNAFnFKzuThAXtYPtTsRHFYPxbezJvzICtjzyigwpfKYIdQrfVCnnxoJTT199 = "ecdQrCIIGYOSfHoRvUlLSsFnVLfHRrzlJvvXbSFBVxBdhBCHNEKjjkmfOwhqTPbyruSRTvgGsMkayFR"
IhjooRSckQuQOkcVQJKonKVctCMcfxetKAwfNeIdkAuadRpWFfDQVXZVnLHtmWaKBPboTBtymQFgdLq201 = 333
d16375891639835763203 = 315
AaAaaAAaaAaAaAaAAAAAAaAAaaAaaaAAAaaAAaaAaaAaAaAAAAaAAAAaAAAAAAAaAAaAAaAaAaAAAaaAaAaaAaAaaaAaAAaAAaAAAaAAAaAAaAaaAaaAaaAAaAAaAaAaAaAAAaAAaAaAaaaaaaaaaAaAaaAaAAAAaaAaAaAaAAaaaAaAAAAaAaAaaAAAAAAAAaaAAAAAaaaAa = 244
WTFWqlfejCRGLOkfVUgAIACnfFWSWbmPYFpoLfmeeyLuMHvSwgBEWZeeBaRVkNQfyxBvjlulbVJNQFq207 = "EvsXHlDyuYSOSPVXqagjWmEBQHKmAsQoiMYchkLmqQeFGOrdXbBsRQRhaTajXWoiFIANCwkagOulUWG"
k16375891639855142209 = "DJUVErwtUjOLZCMQlaAdqsyqZUkBRQYbOjvgdhvzCEAHpAfRoPWUDuEubqHSzaDIQfPUvxcCKdVumAb"
a211 = 228
x16375891639858787213 = 289
ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp = 377
AaAaaAAaAAAaAAAAaAAAaaAAAAAaaaAaaAAaaAaaaAaaAAAAaaAaaAAaaAAAAaaAaaaAAAaaaAAaaAaaaaAAaaaaAaaAAAAAaAaaAaaAAaAAaaAaaAAaaAAaaaaAaAAaaAAaAaAaAaaaAaaaAAaaAAAaAaaAAAAaaaaaaaaAaaAAaAaAAaAaAaaaAAaAaAAaAaaaAAaAAaaAAaAaaAAAaAAAa = 292
AaaaaaAAAaaaAAaAaaAaAaAAaaAAaAaaAaaaaaAaaaAaaAAaaAaAAAAaaAaaaaAAAaaAAaaAAAAAAaaAaaAAaAAAaaAAAAAaaAAAaaaaaAaaAaaaaaAaaAaAaaAAAaaaaaaaAAaaaaAAAAAAAaAaAaAaAaAAaaAAaaaAAAaaaaaAAaaaaAaaaaAaAaaAaAAaAAAAAaAAAAaaAaaaAAaaAAAAAAa = "cuEvcMwqBGdiIyecpixAQYoeVeGNJwuUZSpApGczRyoCviJdRlQpPZbkehgGiNEIHwEuNMukEbWwAZf"
aAaaAaaAaAaAAaaAaaaaaaaAAaAaAaAAaAaAAaaaAAaAAaaAaAaAAaAAAaAAaAaaAAAaaAaaaaAAaAaAAaaaAAAAaaaaAAaAaAAAaaAaAaaAAAaaaAaaaAaaAaAAAAAaaaaAaAaaAaaAAAAaaAAAAAAAaAaAaaaaaAaaAAaAAAAaAaaaaAAaAaAaAAAAAaAaaaAaaAaaAAaAAaaAaAaAaaAaAAaaa = 727
F223 = 362
IIlllIllIlIIllIIlllIlIlIlIllllllIIIIIIIlIIIlllIllIllIllIIIIllIIIlIIllIIIIIIlllIIIlIIIIIIIllIllIlIlIIIllIIIIlllIIlIIIIlIIlIlIIllIlIIlIIlllIIlIllIlIlIllIIlllllIlllIlIlIlIlIlllIIIIIIIlIlIlIllIllIIIIIIlIIIIIIllIIllIlIIIIIllllIllI = 684
aaAaaAaaAaaAAaAAaaaaaaAaAAaaaaaAaAAAAaaAaaAAAaAAAAAAAAaAaaaAAaAAAaAaaAAAaaAaaAAAaaAaAaAAAaAaaAAAAaAaAaAaaAAAaAAAAAaAaAaaaAAaAaaaaAaaAAaaaaAAaaAaaAaAAaAaAaaaaAaaaaaAaaaAaaAAAaAAaAaAaaAAAaAAaaaaAaAaaAAaaaAaAaaaAaaAAaaaaAAaAaAaAaA = "PplQbAvFhlNZCaRhGxBgymuOBQORKPnDepCrvNMaONdHwxlGgSdhqAQnoXwHOrsxApSdxejkovDgaCp"
AOMRJdnpWfAHzpOHsMwtzZcjKtTzYuGJkpndUzXOmCdSKpjCtHLgcAJxHDVOmjNgyJEtQsdhYXYHFke229 = 773
d16375891639898095231 = 288
lIIllIIlIIllllIlIIIllIIIlIlIlIIIIllIllIllIIIlIlIIlIIIllIllIIIIIIIIIllllIIIIlIlIlIIIlIllIIlIIIIIIIlIllIlIllIllllIIllIIIlllIlIIlllllIIIIlIlIIIIlIIIIllllIIlIllllIlIIIIlIlIlllllllIIIIllIIllIIIlllIllllIllIlIlIlIllIIIIIlIIlllIllIllIIIlIIll = 226
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC = 279
yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy = "tmYtLoiEYQdefjXuzLycxxqhwWNZdvUHNrOZgaLrEPpyzPXOseVfhAbDMDiPRYIrOqzNGFIKtydDPkz"
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss = 204
aaAAaaAaaAAAAaaaAAAaaaAaaaAAAAaAAaaAAAaaaaAAAAaAAAaAaaAAaaAaAaaAaaaaaaaaaaaAaAAaAaAAAAAAAAaAAaAaaaAaaaaAaAAAAAaaaAaaAAAAaAAAAaAAaaAAAAAAaaAAaAAaAAaaaAAaaaaaAAaaaaAAAaaAaaaAaaaaaAAaaaAAaAAAaAAaAaaAaaAAaAAAAAAAAaAaAaaAaaAAaAAAaaAaaAaAAaaAaAAaa = 301
XdCxCxZdFxbkWRHjpYHlxstHOgsGyzwYIUShfwdEfcAWULgjzHOpUGdUKGzwartdOvvfLbgPhwpXNCG243 = "WnvlPlZLPSHKnUjXhUXOVdVUgFwylFISRyluMWZJqOiXGPVvGUmHArcMKnPEqwtbJPSoZzbwWYQPKdv"
AAaaaAAAAaaAAaaAAAaaaAAAAaaaAaAAaaAaaaaAaAAAAAaAaAaAAaaAAAaaaaaaaaaaaAaaaaAAAaaaaAaaAAAaaAaAaaaaaAAaAaAaaAaaaAAaaAAaAAaaaaaaaaaAaAAaaaAAaAAAAaaAAaAAaaaAAAaAAaaAaaaAaaaaaAAaAAAAaAaaAaaaAaAAAaAaAaAAaAAAaaaaaaaAaaaAAAaaAaaaaaaAAaaAaAAaAaaAaAaaAAAaA = 420
aAAAaAAaaAaaaAaaaaaAAAaaaaAaAaAaaAAaAaaaAaaaaAAAAaAaAaAAAaAaaAaaAAAaaaAaaaAaAAaaaaAaAAAAaaAaaAAAaAAAAaAAaAaAaaaAAAAAaaaAaAaAAAAAaaaAAAaAAAAaAaaAAAAAAAAAaAAaaAAaAAAAaaaAaaaAaaaaAaAAaaAAAaaaaaAAaAAAaaAaaaaaAAAaaAaAAAaaAaAaaaaAAAaAaAAAaAAAAAaaAaAaAaA = "uMYnvQcslmoYUvmTJnaFaBeyuTaECUYmTfCbXJSnaAOVyBwlLzczyRAubzrHAweyZPOVvpgoRfwdsEP"
k249 = 304
RWWhEcJCYPVgxXgXcLzMUtCCDuDdtjTzVMbyhNwEzBFbvMEcKwIwQIWRqGOdiyMSwQZLwnbYZRHaYPP251 = "GOtVRblKEOEXidtZtnWWYPrsbZzyXCIzTszilBDvGxQGBTQRnNOjtVxTrjHHfHrTDWOuifbRXRVzrOh"
ViNXSkLAclJcIduFwxcDxHZCLPTxIZGrrvGFyPgRObYLslSNuUuHwqelUuBoxmPCRjzvWuStjlCazyw253 = 359
AaAAaaaaaaaAaAAaAAAaAAAaAaAaaAAAAaAAAAAaAaAAaaAAaAAAaaaaAAaaAaAAaAaaAAaAAAaAAaaaAAAaAaaaaAAAAaaAaaAaAaAAAAAAAaAaAaaAAAaAAAaAaAAAAAaaAAaaaAAAaaAaAaaAaaAAAaAaaAAAaaAAAAAAAaaAAaaAAAAaaaaAaAAaAaAAAAaaAAAAAaaaAAaAAAaAAaaAAAAaaaAaAAAaaaAAAAAaaaaAAaAAaAAAaAAAaAa = 298
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr = 76
lllIlIIlllIIIIIlllIlIIIlIIIlIllIIIIIlIllIlIlIllIlIIllIllIIIIIllllIIllIllllIlIIIIIIIIlIIIIIlllIIIllllllIllIIIIlIllIllIIIlllIIlllllIIIlIIIIlllIIllIIlIlIIIIlIlIllIllIlIllIlllllIllIIIIlIlIlIIIlIlllIIIIIllIIIIIlIlIllllIIIlIIIllIllIlIIlIIIllIlIIlllllIIIllIIlIIllIlI = 734
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = "VwBNEDBMHonzthlJjkUYaCtRCckBWMfvyeKNBSjRyEvZlJQaeThttKhDhNurkQXkHGuJKnKCgOFjGlY"